<?php
/**
 * Bullseye plan specification module.
 */

// constant access arguments
define('BULLSEYE_PRODUCER_FILE_VIEW', 'View File browser');

/**
 * Implements hook_menu().
 */
function bullseye_producer_file_menu() {
  $items = array();

  $items['producer_file_browser'] = array(
    'title' => 'Files',
    'page callback' => 'bullseye_producer_file_page',
    'access arguments' => array(BULLSEYE_PRODUCER_FILE_VIEW),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
/**
 * implementation of hook permission
 */
function bullseye_producer_file_permission(){
  return array(
    BULLSEYE_PRODUCER_FILE_VIEW => array(
      'title' => t(BULLSEYE_PRODUCER_FILE_VIEW),
      'description' => t('Allow users on adding plan specifications.'),
    ),
  );
}

/**
 * helper function
 * checks if the user can access the directory
 */
function bullseye_producer_file_directory_access($directory_name = ''){
  return true;
}


/**
 * file browser page for producers
 */
function bullseye_producer_file_page(){
  // global $base_url; //krumo(node_load(5321));

  // // Theme directory.
  // $theme_directory = path_to_theme('theme', 'bullseye');

  // $producer_acct_company_img = $base_url . '/' . $theme_directory . '/images/icons/producer-acct-company-logo.jpg';
  $total_files = bullseye_producer_file_get_file_total();
  $vars = array(
    'directory_html' => bullseye_producer_file_directory_render(),
    'files_html' => bullseye_producer_file_files_table_render(),
    'total_files' => $total_files,
  );

  return theme('producer_file_browser', $vars);
}

/**
 * helper function
 * retrieve total file numbers
 */
function bullseye_producer_file_get_file_total(){
  return 4;
}

/**
 * renders the directory as tree view
 */
function bullseye_producer_file_directory_render(){
  $directory = bullseye_producer_file_directory_user_load();
  $vars = array(
    'directory' => $directory,
  );

  return theme('bullseye_producer_file_directory', $vars);
}

/**
 * renders the files as tables
 */
function bullseye_producer_file_files_table_render(){
  $directory = bullseye_producer_file_directory_user_load();
  $files = bullseye_producer_file_get_all_files();
  $vars = array(
    'directory' => $directory,
    'files' => $files,
  );

  return theme('bullseye_producer_file_files_table', $vars);
}

/**
 * helper function
 * get all files of each directory
 */
function bullseye_producer_file_get_all_files(){
  // example only
  $files = array(
    'Arrow Trust Docs' => array(
      'type' => 'doc',
      'account' => 'ABC Company',
      'upload_date' => '05/20/2017',
      'upload_name' => 'James J.',
      'last_access' => '05/20/2017',
    ),
    'Benefits Enrollment Guide' => array(
      'type' => 'pdf',
      'account' => 'Gekko & Co',
      'upload_date' => '04/13/2017',
      'upload_name' => 'Mikka C.',
      'last_access' => '04/13/2017',
    ),
    'Employee Manual' => array(
      'type' => 'pptx',
      'account' => 'ABC Company',
      'upload_date' => '06/01/2017',
      'upload_name' => 'Beata S.',
      'last_access' => '06/01/2017',
    ),
    'Monthly Benefits Computation' => array(
      'type' => 'xlsx',
      'account' => 'Umbrella Corporation',
      'upload_date' => '05/01/2017',
      'upload_name' => 'James J.',
      'last_access' => '05/01/2017',
    ),
  );
  return $files;
}

/**
 * helper function
 * load content directories available for users
 */
function bullseye_producer_file_directory_user_load($directory_name = ''){
  // example data only
  return _bullseye_producer_file_tree_process_sample();

  // actual logic should load all the directories that the user can access
}

/**
 * test function
 * sample data provided for the tree process
 */
function _bullseye_producer_file_tree_process_sample(){
  return array(
    'ABC Company' => array(
      '2017',
    ),
    'Gekko & Co.' => array(
      '2017',
    ),
  );
}