<?php
/**
 * Dashboard module file.
 */

/**
 * Implements hook_init().
 */
function bullseye_dashboard_init() {
  if (drupal_is_front_page()) {
    $wr = 0;
    if (Bullseye::winRatioDashboard()) {
      $wr = Bullseye::winRatioDashboard();
    }
    drupal_add_js(
      array(
        'dashboard' => array(
          'win_ratio' => $wr,
        ),
      ),
      array('type' =>'setting')
    );
  }
}
