<?php
/**
 * RFP module file.
 *
 * @author
 *  Gerald Villorente
 */

/**
 * DOMPDF library.
 */
require_once 'dompdf/autoload.inc.php';
use Dompdf\Dompdf;
use Dompdf\Options;

/**
 * Implements hook_menu().
 */
function bullseye_rfp_menu() {
  $items = array();

  $items['rfps/add'] = array(
    'title' => 'Create New RFP',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bullseye_rfp_form'),
    'access arguments' => array('add rfp'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['rfps/initial-add'] = array(
    'title' => 'Create New RFP',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bullseye_rfp_initial_add_form'),
    'access arguments' => array('add rfp'),
    'type' => MENU_NORMAL_ITEM,
  );

  // Config Sesssion for BullsEye.
  $items['admin/config/bullseye'] = array(
    'title' => 'BullsEye Settings',
    'description' => 'Settings related to BullsEye',
    'weight' => -30,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'position' => 'right',
  );

  // Derusni premium configuration page.
  $items['admin/config/bullseye/rfp'] = array(
    'title' => 'RFP Settings',
    'description' => 'RFP settings page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bullseye_rfp_admin_form'),
    'access arguments' => array('administer rfp settings'),
    'file' => 'bullseye_rfp.admin.inc',
    'file path' => drupal_get_path('module', 'bullseye_rfp'),
    'weight' => 5,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function bullseye_rfp_permission() {
  return array(
    'add rfp' => array(
      'title' => t('Create new RFP'),
      'description' => t('Allow user to add new rfp.'),
    ),
    'administer rfp settings' => array(
      'title' => t('Administer RFP'),
      'description' => t('Allow user to manage RFP settings.'),
    ),
  );
}

/**
 * Implements hook_form().
 *
 * Add RFP form (initial form popup).
 */
function bullseye_rfp_initial_add_form($form, &$form_state) {

  $form = array();

  $form['#attributes']['class'][] = 'be-forms be-forms-custom';

  $form['form_title'] = array(
    '#prefix' => '<div class="form-title">',
    '#suffix' => '</div>',
    '#markup' => '<h2>' . t('Create New RFP') . '</h2>',
  );

  $form['account'] = array(
    '#required' => FALSE,
    '#type' => 'entityreference',
    '#title' => t('Select Account'),
    '#era_entity_type' => 'node',
    '#era_bundles' => array('accounts'),
    '#era_cardinality' => 1,
    '#era_query_settings' => array(
      'limit' => 15, // Default is 50.
      'property_conditions' => array(
        array('status', 1, '='),
      ),
      'field_conditions' => array(),
    ),
  );

  $form['benefits_container'] = array(
    '#type' => 'container',
    'benefits' => array(),
  );

  $form['benefits_container']['benefits']['major_medical'] = array(
    '#type' => 'checkbox',
    '#title' => t('Major Medical'),
  );

  $form['benefits_container']['benefits']['limited_medical'] = array(
    '#type' => 'checkbox',
    '#title' => t('Limited Medical'),
  );

  $form['benefits_container']['benefits']['teledoc'] = array(
    '#type' => 'checkbox',
    '#title' => t('Telemedicine'),
  );

  $form['benefits_container']['benefits']['mec'] = array(
    '#type' => 'checkbox',
    '#title' => t('MEC'),
  );

  $form['benefits_container']['benefits']['life'] = array(
    '#type' => 'checkbox',
    '#title' => t('Life & AD&D'),
  );

  $form['benefits_container']['benefits']['short_term_disability'] = array(
    '#type' => 'checkbox',
    '#title' => t('Short Term Disability'),
  );

  $form['benefits_container']['benefits']['dental'] = array(
    '#type' => 'checkbox',
    '#title' => t('Dental'),
  );

  $form['benefits_container']['benefits']['vision'] = array(
    '#type' => 'checkbox',
    '#title' => t('Vision'),
  );

  $form['benefits_container']['benefits']['retirement'] = array(
    '#type' => 'checkbox',
    '#title' => t('Retirement'),
  );

  $form['benefits_container']['benefits']['special_benefits'] = array(
    '#type' => 'checkbox',
    '#title' => t('Special Benefits'),
  );

  $form['special_benefits_text'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Enter special benefit'),
    ),
  );

  $form['submit_container'] = array(
    '#type' => 'container',
  );

  $form['submit_container']['cancel'] = array(
    '#markup' => '<a class="gray-btn" href="/" onClick="parent.Lightbox.end();">Cancel</a>',
  );

  $form['submit_container']['submit'] = array(
    '#type' => 'submit',
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
    '#value' => t('Next'),
  );

  return $form;
}

/**
 * Form submit for initial create RFP Form.
 */
function bullseye_rfp_initial_add_form_submit($form, &$form_state) {
  // Clear session first.
  unset($_SESSION['add_rfp']);

  $account = node_load($form_state['values']['account']['entity_id']);
  $query = '/rfps/add?';
  $query .= 'account_name=' . $account->title;

  // Save the data temporarily to session variable.
  $_SESSION['add_rfp'] = array(
    'account_id' => $form_state['values']['account']['entity_id'],
    'major_medical' => $form_state['values']['major_medical'],
    'limited_medical' => $form_state['values']['limited_medical'],
    'teledoc' => $form_state['values']['teledoc'],
    'mec' => $form_state['values']['mec'],
    'life' => $form_state['values']['life'],
    'short_term_disability' => $form_state['values']['short_term_disability'],
    'dental' => $form_state['values']['dental'],
    'vision' => $form_state['values']['vision'],
    'retirement' => $form_state['values']['retirement'],
    'special_benefits' => $form_state['values']['special_benefits'],
    'special_benefits_text' => $form_state['values']['special_benefits_text'],
  );

  $benefits = array();

  // Prepare benefits data before passing to url parameter.
  foreach ($form_state['complete form']['benefits_container']['benefits'] as $key => $value) {
    if ($key[0] != '#') {
      $benefits[$key] = $value['#value'];
    }
  }

  // Build the parameter query for benefits array.
  $benefits_query = http_build_query(
    array(
      'benefits' => $benefits,
      'from_current_progress' => FALSE,
      'plan_specs' => FALSE,
    )
  );
  $query .= '&' . $benefits_query;

  // Close the lightbox and redirect to the next create new RFP page.
  print '<script>parent.location = "' . $query . '";</script>';
  print '<script>parent.Lightbox.end();</script>';
  die();
}

/**
 * Implements hook_form().
 *
 * Add RFP form.
 */
function bullseye_rfp_form($form, &$form_state) {

  $form = array();

  $form['#attributes']['class'][] = 'be-forms be-forms-custom';

  $fringe_rates = '';
  $proposed_effective_date = '';
  $other_work_locations = '';
  $number_of_employees = '';
  $number_of_dependents = '';
  $nature_of_business = '';
  $years_in_business = '';
  $tax_id = '';
  $renewal_date = '';

  if (isset($_GET['plan_specs']) && $_GET['plan_specs'] && !empty($_GET['plan_specs'])) {
    $fringe_rates = $_GET['plan_specs']['fringe_rates'];
    $proposed_effective_date = $_GET['plan_specs']['proposed_effective_date'];
    $other_work_locations = $_GET['plan_specs']['other_work_locations'];
    $number_of_employees = $_GET['plan_specs']['number_of_employees'];
    $number_of_dependents = $_GET['plan_specs']['number_of_dependents'];
    $nature_of_business = $_GET['plan_specs']['nature_of_business'];
    $years_in_business = $_GET['plan_specs']['years_in_business'];
    $tax_id = $_GET['plan_specs']['tax_id'];
    $renewal_date = $_GET['plan_specs']['renewal_date'];
  }

  // RFP Due Date.
  $form['rfp_due_date'] = array(
    '#type' => 'date_popup',
    '#date_format' => 'm/d/Y',
    '#date_year_range' => '0:+3',
    '#default_value' => 'now',
  );

  // Fringe Rate/s.
  $form['fringe_rates'] = array(
    '#type' => 'textfield',
    '#title' => t('Fringe Rate/s'),
    '#attributes' => array(
      'placeholder' => '500',
    ),
    '#default_value' => $fringe_rates,
  );

  // Proposed Effective Date.
  $form['proposed_effective_date'] = array(
    '#type' => 'date_popup',
    '#date_format' => 'm/d/Y',
    '#default_value' => $proposed_effective_date,
    '#date_year_range' => '0:+3',
    '#title' => t('Proposed Effective Date'),
  );

  // Other Work Locations and Zip Codes.
  $form['other_work_locations'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Work Locations and Zip Codes'),
    '#attributes' => array(
      'placeholder' => 'Dallas 88829, New Jersey 81920',
    ),
    '#default_value' => $other_work_locations,
  );

  // Number of Employees.
  $form['number_of_employees'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Employees'),
    '#attributes' => array(
      'placeholder' => '100',
    ),
    '#default_value' => $number_of_employees,
  );

  // Number of Dependents.
  $form['number_of_dependents'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Dependents'),
    '#attributes' => array(
      'placeholder' => '200',
    ),
    '#default_value' => $number_of_dependents,
  );

  // Nature of Business/SIC.
  $form['nature_of_business'] = array(
    '#type' => 'textfield',
    '#title' => t('Nature of Business/SIC'),
    '#attributes' => array(
      'placeholder' => 'xxxx',
    ),
    '#default_value' => $nature_of_business,
  );

  // Years in Business.
  $form['years_in_business'] = array(
    '#type' => 'textfield',
    '#title' => t('Years in Business'),
    '#attributes' => array(
      'placeholder' => '5',
    ),
    '#default_value' => $years_in_business,
  );

  // Tax ID.
  $form['tax_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Tax ID'),
    '#attributes' => array(
      'placeholder' => 'xxxxxxxxx',
    ),
    '#default_value' => $tax_id,
  );

  // Renewal Date.
  $form['renewal_date'] = array(
    '#type' => 'date_popup',
    '#date_format' => 'm/d/Y',
    '#default_value' => $renewal_date,
    '#date_year_range' => '0:+3',
    '#title' => t('Renewal Date'),
  );

  // Attachments.
  $form['attachments_container'] = array(
    '#type' => 'container',
    'attachment' => array(),
  );

  $form['attachments_container']['attachment']['employee_census'] = array(
    '#title' => t('Employee Census'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['current_summary_of_benefit'] = array(
    '#title' => t('Current Summary of Benefit'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['current_bill'] = array(
    '#title' => t('Current Bill'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['last_renewal_letter'] = array(
    '#title' => t('Last Renewal Letter & Rates'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['summary_of_monthly_claims_experience'] = array(
    '#title' => t('Summary of Monthly Claims Experience'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['broker_of_record'] = array(
    '#title' => t('Broker of Record'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['letter_of_authorization'] = array(
    '#title' => t('Letter of Authorization'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['large_claims_report'] = array(
    '#title' => t('Large Claims Report'),
    '#type' => 'managed_file',
  );

  // Census checkboxes.
  $form['census_container'] = array(
    '#type' => 'container',
    'census' => array(),
  );

  $form['census_container']['census']['check_identifier'] = array(
    '#type' => 'checkbox',
    '#title' => t('Identifier (Name or Employee Number)'),
  );

  $form['census_container']['census']['check_ssn'] = array(
    '#type' => 'checkbox',
    '#title' => t('Social Security Number'),
  );

  $form['census_container']['census']['check_date_birth_age'] = array(
    '#type' => 'checkbox',
    '#title' => t('Date of Birth or Age'),
  );

  $form['census_container']['census']['check_gender'] = array(
    '#type' => 'checkbox',
    '#title' => t('Gender'),
  );

  $form['census_container']['census']['check_home_zip_codes'] = array(
    '#type' => 'checkbox',
    '#title' => t('Home Zip Codes for each employee'),
  );

  $form['census_container']['census']['check_plan_selection'] = array(
    '#type' => 'checkbox',
    '#title' => t('Plan Selection (HMO, PPO, HSA, etc.)'),
  );

  $form['census_container']['census']['check_tier_levels'] = array(
    '#type' => 'checkbox',
    '#title' => t('Tier Levels (EE, ES, EC(H), EF) or 3 Tiers (if applicable)'),
  );

  $form['census_container']['census']['check_identification_of_retirees'] = array(
    '#type' => 'checkbox',
    '#title' => t('Identification of Retirees or COBRA members with COBRA Termination Date'),
  );

  $form['census_container']['census']['check_identification_of_covered'] = array(
    '#type' => 'checkbox',
    '#title' => t('Identification of covered and not covered employees with explanation for those not (i.e. spousal, medicare, medicaid, etc.)'),
  );

  $form['carrier_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Carrier Name'),
  );

  $form['primary_contact_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Primary Contact'),
  );

  $form['primary_contact_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email Address'),
  );

  $form['major_medical'] = array(
    '#type' => 'checkbox',
    '#title' => t('Major Medical'),
    '#default_value' => $_GET['benefits']['major_medical'],
  );

  $form['limited_medical'] = array(
    '#type' => 'checkbox',
    '#title' => t('Limited Medical'),
    '#default_value' => $_GET['benefits']['limited_medical'],
  );

  $form['teledoc'] = array(
    '#type' => 'checkbox',
    '#title' => t('Teledoc'),
    '#default_value' => $_GET['benefits']['teledoc'],
  );

  $form['mec'] = array(
    '#type' => 'checkbox',
    '#title' => t('MEC'),
    '#default_value' => $_GET['benefits']['mec'],
  );

  $form['dental'] = array(
    '#type' => 'checkbox',
    '#title' => t('Dental'),
    '#default_value' => $_GET['benefits']['dental'],
  );

  $form['vision'] = array(
    '#type' => 'checkbox',
    '#title' => t('Vision'),
    '#default_value' => $_GET['benefits']['vision'],
  );

  $form['life'] = array(
    '#type' => 'checkbox',
    '#title' => t('Life & AD&D'),
    '#default_value' => $_GET['benefits']['life'],
  );

  $form['short_term_disability'] = array(
    '#type' => 'checkbox',
    '#title' => t('Short Term Dissability'),
    '#default_value' => $_GET['benefits']['short_term_disability'],
  );

  $form['special_benefits'] = array(
    '#type' => 'checkbox',
    '#title' => t('Special Benefits'),
    '#default_value' => $_GET['benefits']['special_benefits'],
  );

  $form['retirement'] = array(
    '#type' => 'checkbox',
    '#title' => t('Retirement'),
    '#default_value' => $_GET['benefits']['retirement'],
  );

  $autocomplete_carriers_1 = array(
    '#required' => FALSE,
    '#type' => 'entityreference',
    '#era_entity_type' => 'node',
    '#era_bundles' => array('carrier'),
    '#era_cardinality' => 1,
    '#era_query_settings' => array(
      'limit' => 15, // Default is 50.
      'property_conditions' => array(
        array('status', 1, '='),
      ),
      'field_conditions' => array(),
    ),
    '#attributes' => array(
      'placeholder' => t('Carrier 1'),
    ),
  );
  $autocomplete_carriers_2 = $autocomplete_carriers_1;
  $autocomplete_carriers_2['#attributes']['placeholder'] = t('Carrier 2');
  $autocomplete_carriers_3 = $autocomplete_carriers_1;
  $autocomplete_carriers_3['#attributes']['placeholder'] = t('Carrier 3');
  $autocomplete_carriers_4 = $autocomplete_carriers_1;
  $autocomplete_carriers_4['#attributes']['placeholder'] = t('Carrier 4');
  $autocomplete_carriers_5 = $autocomplete_carriers_1;
  $autocomplete_carriers_5['#attributes']['placeholder'] = t('Carrier 5');

  // Major Medical.
  $form['major_medical_fields'] = array(
    '#type' => 'container',
    'mm_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'mm_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'mm_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'mm_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'mm_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'mm_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'mm_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'mm_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
    'major_medical_attach_ec' => array(
      '#type' => 'checkbox',
      '#title' => t('Employee Census'),
    ),
    'major_medical_attach_csob' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Summary of Benefit'),
    ),
    'major_medical_attach_cb' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Bill'),
    ),
    'major_medical_attach_lrlr' => array(
      '#type' => 'checkbox',
      '#title' => t('Last Renewal Letter & Rates'),
    ),
    'major_medical_attach_somce' => array(
      '#type' => 'checkbox',
      '#title' => t('Summary of Monthly Claims Experience'),
    ),
    'major_medical_attach_bor' => array(
      '#type' => 'checkbox',
      '#title' => t('Broker of Record'),
    ),
    'major_medical_attach_loa' => array(
      '#type' => 'checkbox',
      '#title' => t('Letter of Authorization'),
    ),
    'major_medical_attach_lcr' => array(
      '#type' => 'checkbox',
      '#title' => t('Large Claims Report'),
    ),
    'mm_carriers_to_send' => array(
      'mm_carrier_to_send_1' => $autocomplete_carriers_1,
      'mm_carrier_to_send_2' => $autocomplete_carriers_2,
      'mm_carrier_to_send_3' => $autocomplete_carriers_3,
      'mm_carrier_to_send_4' => $autocomplete_carriers_4,
      'mm_carrier_to_send_5' => $autocomplete_carriers_5,
    ),
  );

  // Limited Medical.
  $form['limited_medical_fields'] = array(
    '#type' => 'container',
    'lm_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'lm_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'lm_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'lm_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'lm_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'lm_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'lm_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'lm_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
    'limited_medical_attach_ec' => array(
      '#type' => 'checkbox',
      '#title' => t('Employee Census'),
    ),
    'limited_medical_attach_csob' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Summary of Benefit'),
    ),
    'limited_medical_attach_cb' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Bill'),
    ),
    'limited_medical_attach_lrlr' => array(
      '#type' => 'checkbox',
      '#title' => t('Last Renewal Letter & Rates'),
    ),
    'limited_medical_attach_somce' => array(
      '#type' => 'checkbox',
      '#title' => t('Summary of Monthly Claims Experience'),
    ),
    'limited_medical_attach_bor' => array(
      '#type' => 'checkbox',
      '#title' => t('Broker of Record'),
    ),
    'limited_medical_attach_loa' => array(
      '#type' => 'checkbox',
      '#title' => t('Letter of Authorization'),
    ),
    'limited_medical_attach_lcr' => array(
      '#type' => 'checkbox',
      '#title' => t('Large Claims Report'),
    ),
    'lm_carriers_to_send' => array(
      'lm_carrier_to_send_1' => $autocomplete_carriers_1,
      'lm_carrier_to_send_2' => $autocomplete_carriers_2,
      'lm_carrier_to_send_3' => $autocomplete_carriers_3,
      'lm_carrier_to_send_4' => $autocomplete_carriers_4,
      'lm_carrier_to_send_5' => $autocomplete_carriers_5,
    ),
  );

  // Telemedicine.
  $form['teledoc_fields'] = array(
    '#type' => 'container',
    'tel_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'tel_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'tel_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'tel_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'tel_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'tel_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'tel_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'tel_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
    'teledoc_attach_ec' => array(
      '#type' => 'checkbox',
      '#title' => t('Employee Census'),
    ),
    'teledoc_attach_csob' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Summary of Benefit'),
    ),
    'teledoc_attach_cb' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Bill'),
    ),
    'teledoc_attach_lrlr' => array(
      '#type' => 'checkbox',
      '#title' => t('Last Renewal Letter & Rates'),
    ),
    'teledoc_attach_somce' => array(
      '#type' => 'checkbox',
      '#title' => t('Summary of Monthly Claims Experience'),
    ),
    'teledoc_attach_bor' => array(
      '#type' => 'checkbox',
      '#title' => t('Broker of Record'),
    ),
    'teledoc_attach_loa' => array(
      '#type' => 'checkbox',
      '#title' => t('Letter of Authorization'),
    ),
    'teledoc_attach_lcr' => array(
      '#type' => 'checkbox',
      '#title' => t('Large Claims Report'),
    ),
    'tel_carriers_to_send' => array(
      'tel_carrier_to_send_1' => $autocomplete_carriers_1,
      'tel_carrier_to_send_2' => $autocomplete_carriers_2,
      'tel_carrier_to_send_3' => $autocomplete_carriers_3,
      'tel_carrier_to_send_4' => $autocomplete_carriers_4,
      'tel_carrier_to_send_5' => $autocomplete_carriers_5,
    ),
  );

  // MEC.
  $form['mec_fields'] = array(
    '#type' => 'container',
    'mec_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'mec_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'mec_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'mec_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'mec_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'mec_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'mec_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'mec_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
    'mec_attach_ec' => array(
      '#type' => 'checkbox',
      '#title' => t('Employee Census'),
    ),
    'mec_attach_csob' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Summary of Benefit'),
    ),
    'mec_attach_cb' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Bill'),
    ),
    'mec_attach_lrlr' => array(
      '#type' => 'checkbox',
      '#title' => t('Last Renewal Letter & Rates'),
    ),
    'mec_attach_somce' => array(
      '#type' => 'checkbox',
      '#title' => t('Summary of Monthly Claims Experience'),
    ),
    'mec_attach_bor' => array(
      '#type' => 'checkbox',
      '#title' => t('Broker of Record'),
    ),
    'mec_attach_loa' => array(
      '#type' => 'checkbox',
      '#title' => t('Letter of Authorization'),
    ),
    'mec_attach_lcr' => array(
      '#type' => 'checkbox',
      '#title' => t('Large Claims Report'),
    ),
    'mec_carriers_to_send' => array(
      'mec_carrier_to_send_1' => $autocomplete_carriers_1,
      'mec_carrier_to_send_2' => $autocomplete_carriers_2,
      'mec_carrier_to_send_3' => $autocomplete_carriers_3,
      'mec_carrier_to_send_4' => $autocomplete_carriers_4,
      'mec_carrier_to_send_5' => $autocomplete_carriers_5,
    ),
  );

  // Dental.
  $form['dental_fields'] = array(
    '#type' => 'container',
    'den_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'den_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'den_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'den_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'den_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'den_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'den_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'den_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
    'dental_attach_ec' => array(
      '#type' => 'checkbox',
      '#title' => t('Employee Census'),
    ),
    'dental_attach_csob' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Summary of Benefit'),
    ),
    'dental_attach_cb' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Bill'),
    ),
    'dental_attach_lrlr' => array(
      '#type' => 'checkbox',
      '#title' => t('Last Renewal Letter & Rates'),
    ),
    'dental_attach_somce' => array(
      '#type' => 'checkbox',
      '#title' => t('Summary of Monthly Claims Experience'),
    ),
    'dental_attach_bor' => array(
      '#type' => 'checkbox',
      '#title' => t('Broker of Record'),
    ),
    'dental_attach_loa' => array(
      '#type' => 'checkbox',
      '#title' => t('Letter of Authorization'),
    ),
    'dental_attach_lcr' => array(
      '#type' => 'checkbox',
      '#title' => t('Large Claims Report'),
    ),
    'den_carriers_to_send' => array(
      'den_carrier_to_send_1' => $autocomplete_carriers_1,
      'den_carrier_to_send_2' => $autocomplete_carriers_2,
      'den_carrier_to_send_3' => $autocomplete_carriers_3,
      'den_carrier_to_send_4' => $autocomplete_carriers_4,
      'den_carrier_to_send_5' => $autocomplete_carriers_5,
    ),
  );

  // Vision.
  $form['vision_fields'] = array(
    '#type' => 'container',
    'vs_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'vs_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'vs_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'vs_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'vs_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'vs_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'vs_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'vs_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
    'vision_attach_ec' => array(
      '#type' => 'checkbox',
      '#title' => t('Employee Census'),
    ),
    'vision_attach_csob' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Summary of Benefit'),
    ),
    'vision_attach_cb' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Bill'),
    ),
    'vision_attach_lrlr' => array(
      '#type' => 'checkbox',
      '#title' => t('Last Renewal Letter & Rates'),
    ),
    'vision_attach_somce' => array(
      '#type' => 'checkbox',
      '#title' => t('Summary of Monthly Claims Experience'),
    ),
    'vision_attach_bor' => array(
      '#type' => 'checkbox',
      '#title' => t('Broker of Record'),
    ),
    'vision_attach_loa' => array(
      '#type' => 'checkbox',
      '#title' => t('Letter of Authorization'),
    ),
    'vision_attach_lcr' => array(
      '#type' => 'checkbox',
      '#title' => t('Large Claims Report'),
    ),
    'vs_carriers_to_send' => array(
      'vs_carrier_to_send_1' => $autocomplete_carriers_1,
      'vs_carrier_to_send_2' => $autocomplete_carriers_2,
      'vs_carrier_to_send_3' => $autocomplete_carriers_3,
      'vs_carrier_to_send_4' => $autocomplete_carriers_4,
      'vs_carrier_to_send_5' => $autocomplete_carriers_5,
    ),
  );

  // Life.
  $form['life_fields'] = array(
    '#type' => 'container',
    'lf_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'lf_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'lf_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'lf_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'lf_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'lf_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'lf_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'lf_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
    'life_attach_ec' => array(
      '#type' => 'checkbox',
      '#title' => t('Employee Census'),
    ),
    'life_attach_csob' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Summary of Benefit'),
    ),
    'life_attach_cb' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Bill'),
    ),
    'life_attach_lrlr' => array(
      '#type' => 'checkbox',
      '#title' => t('Last Renewal Letter & Rates'),
    ),
    'life_attach_somce' => array(
      '#type' => 'checkbox',
      '#title' => t('Summary of Monthly Claims Experience'),
    ),
    'life_attach_bor' => array(
      '#type' => 'checkbox',
      '#title' => t('Broker of Record'),
    ),
    'life_attach_loa' => array(
      '#type' => 'checkbox',
      '#title' => t('Letter of Authorization'),
    ),
    'life_attach_lcr' => array(
      '#type' => 'checkbox',
      '#title' => t('Large Claims Report'),
    ),
    'lf_carriers_to_send' => array(
      'lf_carrier_to_send_1' => $autocomplete_carriers_1,
      'lf_carrier_to_send_2' => $autocomplete_carriers_2,
      'lf_carrier_to_send_3' => $autocomplete_carriers_3,
      'lf_carrier_to_send_4' => $autocomplete_carriers_4,
      'lf_carrier_to_send_5' => $autocomplete_carriers_5,
    ),
  );

  // Short Term Disability.
  $form['short_term_disability_fields'] = array(
    '#type' => 'container',
      'std_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'std_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'std_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'std_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'std_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'std_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'std_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'std_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
    'short_term_disability_attach_ec' => array(
      '#type' => 'checkbox',
      '#title' => t('Employee Census'),
    ),
    'short_term_disability_attach_csob' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Summary of Benefit'),
    ),
    'short_term_disability_attach_cb' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Bill'),
    ),
    'short_term_disability_attach_lrlr' => array(
      '#type' => 'checkbox',
      '#title' => t('Last Renewal Letter & Rates'),
    ),
    'short_term_disability_attach_somce' => array(
      '#type' => 'checkbox',
      '#title' => t('Summary of Monthly Claims Experience'),
    ),
    'short_term_disability_attach_bor' => array(
      '#type' => 'checkbox',
      '#title' => t('Broker of Record'),
    ),
    'short_term_disability_attach_loa' => array(
      '#type' => 'checkbox',
      '#title' => t('Letter of Authorization'),
    ),
    'short_term_disability_attach_lcr' => array(
      '#type' => 'checkbox',
      '#title' => t('Large Claims Report'),
    ),
    'std_carriers_to_send' => array(
      'std_carrier_to_send_1' => $autocomplete_carriers_1,
      'std_carrier_to_send_2' => $autocomplete_carriers_2,
      'std_carrier_to_send_3' => $autocomplete_carriers_3,
      'std_carrier_to_send_4' => $autocomplete_carriers_4,
      'std_carrier_to_send_5' => $autocomplete_carriers_5,
    ),
  );

  // Retirement.
  $form['retirement_fields'] = array(
    '#type' => 'container',
    'ret_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'ret_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'ret_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'ret_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'ret_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'ret_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'ret_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'ret_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
    'retirement_attach_ec' => array(
      '#type' => 'checkbox',
      '#title' => t('Employee Census'),
    ),
    'retirement_attach_csob' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Summary of Benefit'),
    ),
    'retirement_attach_cb' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Bill'),
    ),
    'retirement_attach_lrlr' => array(
      '#type' => 'checkbox',
      '#title' => t('Last Renewal Letter & Rates'),
    ),
    'retirement_attach_somce' => array(
      '#type' => 'checkbox',
      '#title' => t('Summary of Monthly Claims Experience'),
    ),
    'retirement_attach_bor' => array(
      '#type' => 'checkbox',
      '#title' => t('Broker of Record'),
    ),
    'retirement_attach_loa' => array(
      '#type' => 'checkbox',
      '#title' => t('Letter of Authorization'),
    ),
    'retirement_attach_lcr' => array(
      '#type' => 'checkbox',
      '#title' => t('Large Claims Report'),
    ),
    'ret_carriers_to_send' => array(
      'ret_carrier_to_send_1' => $autocomplete_carriers_1,
      'ret_carrier_to_send_2' => $autocomplete_carriers_2,
      'ret_carrier_to_send_3' => $autocomplete_carriers_3,
      'ret_carrier_to_send_4' => $autocomplete_carriers_4,
      'ret_carrier_to_send_5' => $autocomplete_carriers_5,
    ),
  );

  // Special Benefits.
  $form['special_benefits_fields'] = array(
    '#type' => 'container',
    'sb_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'sb_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'sb_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'sb_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'sb_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'sb_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'sb_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'sb_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
    'special_benefits_attach_ec' => array(
      '#type' => 'checkbox',
      '#title' => t('Employee Census'),
    ),
    'special_benefits_attach_csob' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Summary of Benefit'),
    ),
    'special_benefits_attach_cb' => array(
      '#type' => 'checkbox',
      '#title' => t('Current Bill'),
    ),
    'special_benefits_attach_lrlr' => array(
      '#type' => 'checkbox',
      '#title' => t('Last Renewal Letter & Rates'),
    ),
    'special_benefits_attach_somce' => array(
      '#type' => 'checkbox',
      '#title' => t('Summary of Monthly Claims Experience'),
    ),
    'special_benefits_attach_bor' => array(
      '#type' => 'checkbox',
      '#title' => t('Broker of Record'),
    ),
    'special_benefits_attach_loa' => array(
      '#type' => 'checkbox',
      '#title' => t('Letter of Authorization'),
    ),
    'special_benefits_attach_lcr' => array(
      '#type' => 'checkbox',
      '#title' => t('Large Claims Report'),
    ),
    'sb_carriers_to_send' => array(
      'sb_carrier_to_send_1' => $autocomplete_carriers_1,
      'sb_carrier_to_send_2' => $autocomplete_carriers_2,
      'sb_carrier_to_send_3' => $autocomplete_carriers_3,
      'sb_carrier_to_send_4' => $autocomplete_carriers_4,
      'sb_carrier_to_send_5' => $autocomplete_carriers_5,
    ),
  );

  // Submit buttons for Benefit Generate RFPs.
  $form['generate_rfp_major_medical'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_major_medical'),
    '#name' => 'generate_rfp_major_medical',
    '#value' => t('Send Email'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_limited_medical'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_limited_medical'),
    '#name' => 'generate_rfp_limited_medical',
    '#value' => t('Send Email'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_teledoc'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_teledoc'),
    '#name' => 'generate_rfp_teledoc',
    '#value' => t('Send Email'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_mec'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_mec'),
    '#name' => 'generate_rfp_mec',
    '#value' => t('Send Email'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_dental'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_dental'),
    '#name' => 'generate_rfp_dental',
    '#value' => t('Send Email'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_vision'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_vision'),
    '#name' => 'generate_rfp_vision',
    '#value' => t('Send Email'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_life'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_life'),
    '#name' => 'generate_rfp_life',
    '#value' => t('Send Email'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_short_term_disability'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_short_term_disability'),
    '#name' => 'generate_rfp_short_term_disability',
    '#value' => t('Send Email'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_retirement'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_retirement'),
    '#name' => 'generate_rfp_retirement',
    '#value' => t('Send Email'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_special_benefits'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_special_benefits'),
    '#name' => 'generate_rfp_special_benefits',
    '#value' => t('Send Email'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  // Submit buttons for Download RFPs.
  $form['generate_rfp_major_medical_dl'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_major_medical_dl'),
    '#name' => 'generate_rfp_major_medical_dl',
    '#value' => t('Download PDF'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_limited_medical_dl'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_limited_medical_dl'),
    '#name' => 'generate_rfp_limited_medical_dl',
    '#value' => t('Download PDF'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_teledoc_dl'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_teledoc_dl'),
    '#name' => 'generate_rfp_teledoc_dl',
    '#value' => t('Download PDF'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_mec_dl'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_mec_dl'),
    '#name' => 'generate_rfp_mec_dl',
    '#value' => t('Download PDF'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_dental_dl'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_dental_dl'),
    '#name' => 'generate_rfp_dental_dl',
    '#value' => t('Download PDF'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_vision_dl'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_vision_dl'),
    '#name' => 'generate_rfp_vision_dl',
    '#value' => t('Download PDF'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_life_dl'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_life_dl'),
    '#name' => 'generate_rfp_life_dl',
    '#value' => t('Download PDF'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_short_term_disability_dl'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_short_term_disability_dl'),
    '#name' => 'generate_rfp_short_term_disability_dl',
    '#value' => t('Download PDF'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_retirement_dl'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_retirement_dl'),
    '#name' => 'generate_rfp_retirement_dl',
    '#value' => t('Download PDF'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  $form['generate_rfp_special_benefits_dl'] = array(
    '#type' => 'submit',
    '#submit' => array('generate_rfp_special_benefits_dl'),
    '#name' => 'generate_rfp_special_benefits_dl',
    '#value' => t('Download PDF'),
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
  );

  // The values for the dropdown box.
  $form['type_options'] = array(
    '#type' => 'value',
    '#value' => array(
      'high' => t('High'),
      'normal' => t('Normal'),
      'low' => t('Low'),
    ),
  );

  $form['priority'] = array(
    '#title' => t('Priority'),
    '#type' => 'select',
    '#description' => "Select the priority level.",
    '#options' => $form['type_options']['#value'],
  );

  $form['due_date'] = array(
    '#type' => 'date_popup',
    '#date_format' => 'm/d/Y',
    '#default_value' => 'YYYY-MM-DD 00:00:00',
    '#date_year_range' => '0:+3',
    '#size' => 12,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save and Exit'),
  );

  return $form;
}

/**
 * Form submit for carrier form.
 */
function bullseye_rfp_form_submit($form, &$form_state) {
  global $user;

  $data = $_SESSION['add_rfp'];
  $account = node_load($data['account_id']);

  // Contact.
  $fcid = $account->field_contacts[LANGUAGE_NONE][0]['value'];
  $contact = field_collection_item_load($fcid);

  $value = $form_state['values'];

  // Map the data to RFP storage entity.
  $node = new stdClass();

  $node->title = 'RFP' . Bullseye::randChars(6);

  $node->type = "rfp";
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;
  $node->uid = $user->uid;
  $node->status = 1;
  $node->promote = 0;
  $node->comment = 0;

  // Cons vars.
  $lang = $node->language;
  $val = 'value';

  /***************
   * Group Info
   ***************/
  // Company.
  $node->field_company[$lang][0][$val] = $account->title;
  // Primary email.
  $node->field_email[$lang][0][$val] = $contact->field_email[LANGUAGE_NONE][0]['value'];
  // Phone number.
  $node->field_phone_number[$lang][0][$val] = $account->field_work_phone[$lang][0][$val];
  // Website.
  $node->field_website[$lang][0][$val] = $account->field_work_website[$lang][0][$val];
  // Company Street Address.
  $node->field_company_street_address[$lang][0][$val] = $account->field_street[$lang][0][$val];
  // City.
  $node->field_city[$lang][0][$val] = $account->field_city[$lang][0][$val];
  // State.
  $node->field_frp_state[$lang][0][$val] = $account->field_state_code[$lang][0][$val];
  // Zip Code.
  $node->field_zip_code[$lang][0][$val] = $account->field_postal_code[$lang][0][$val];
  // Due date.
  $node->field_due_date[$lang][0][$val] = $value['rfp_due_date'];

  /**************
   * Plan Specifications
   **************/
  // Fringe Rate.
  $node->field_fringe_rate[$lang][0][$val] = $value['fringe_rates'];
  // Proposed Effective Date.
  $node->field_proposed_effective_date[$lang][0][$val] = $value['proposed_effective_date'];
  // Other Work Locations and Zip Codes.
  $node->field_other_work_locations[$lang][0][$val] = $value['other_work_locations'];
  // Number of Employees.
  $node->field_number_of_employees[$lang][0][$val] = $value['number_of_employees'];
  // Number of Dependents.
  $node->field_number_of_dependents[$lang][0][$val] = $value['number_of_dependents'];
  // Nature of Business/SIC.
  $node->field_nature_of_business_sic[$lang][0][$val] = $value['nature_of_business'];
  // Years in Business.
  $node->field_years_in_business[$lang][0][$val] = $value['years_in_business'];
  // Tax ID.
  $node->field_tax_id[$lang][0][$val] = $value['tax_id'];
  // Renewal Date.
  $node->field_renewal_date[$lang][0][$val] = $value['renewal_date'];

  /*************
   * Benefits
   *************/
  // Major Medical.
  // Current carrier.
  $node->field_mm_current_carrier[$lang][0][$val] = $value['mm_current_carrier'];
  // Years with current carrier.
  $node->field_mm_years_current_carrier[$lang][0][$val] = $value['mm_years_with_current_carrier'];
  // Plan Year to Quote.
  $node->field_mm_plan_start[$lang][0][$val] = $value['mm_plan_year_to_quote_start'];
  $node->field_mm_plan_end[$lang][0][$val] = $value['mm_plan_year_to_quote_end'];
  // Is this a renewal of a current plan in BullsEye?
  $node->field_mm_renewal_current_plan_be[$lang][0][$val] = $value['mm_renewal_of_current_plan'];
  // Percentage of Employer Contribution.
  $node->field_mm_contrib_single[$lang][0][$val] = $value['mm_percentage_single'];
  $node->field_mm_contrib_family[$lang][0][$val] = $value['mm_percentage_family'];
  // Waiting Period for New Employees?
  $node->field_mm_waiting_period[$lang][0][$val] = $value['mm_waiting_period'];

  // Limited Medical.
  // Current Carrier.
  $node->field_lm_current_carrier[$lang][0][$val] = $value['lm_current_carrier'];
  // Years with current carrier.
  $node->field_lm_years_current_carrier[$lang][0][$val] = $value['lm_years_with_current_carrier'];
  // Plan Year to Quote.
  $node->field_lm_plan_start[$lang][0][$val] = $value['lm_plan_year_to_quote_start'];
  $node->field_lm_plan_end[$lang][0][$val] = $value['lm_plan_year_to_quote_end'];
  // Is this a renewal of a current plan in BullsEye?
  $node->field_lm_renewal_current_plan_be[$lang][0][$val] = $value['lm_renewal_of_current_plan'];
  // Percentage of Employer Contribution.
  $node->field_lm_contrib_single[$lang][0][$val] = $value['lm_percentage_single'];
  $node->field_lm_contrib_family[$lang][0][$val] = $value['lm_percentage_family'];
  // Waiting Period for New Employees?
  $node->field_lm_waiting_period[$lang][0][$val] = $value['lm_waiting_period'];

  // Teledoc.
  // Current Carrier.
  $node->field_tl_current_carrier[$lang][0][$val] = $value['tel_current_carrier'];
  // Years with current carrier.
  $node->field_tl_years_current_carrier[$lang][0][$val] = $value['tel_years_with_current_carrier'];
  // Plan Year to Quote.
  $node->field_tl_plan_start[$lang][0][$val] = $value['tel_plan_year_to_quote_start'];
  $node->field_tl_plan_end[$lang][0][$val] = $value['tel_plan_year_to_quote_end'];
  // Is this a renewal of a current plan in BullsEye?
  $node->field_tl_renewal_current_plan_be[$lang][0][$val] = $value['tel_renewal_of_current_plan'];
  // Percentage of Employer Contribution.
  $node->field_tl_contrib_single[$lang][0][$val] = $value['tel_percentage_single'];
  $node->field_tl_contrib_family[$lang][0][$val] = $value['tel_percentage_family'];
  // Waiting Period for New Employees?
  $node->field_tl_waiting_period[$lang][0][$val] = $value['tel_waiting_period'];

  // MEC.
  // Current Carrier.
  $node->field_mec_current_carrier[$lang][0][$val] = $value['mec_current_carrier'];
  // Years with current carrier.
  $node->field_mec_years_current_carrier[$lang][0][$val] = $value['mec_years_with_current_carrier'];
  // Plan Year to Quote.
  $node->field_mec_plan_start[$lang][0][$val] = $value['mec_plan_year_to_quote_start'];
  $node->field_mec_plan_end[$lang][0][$val] = $value['mec_plan_year_to_quote_end'];
  // Is this a renewal of a current plan in BullsEye?
  $node->field_mc_renewal_current_plan_be[$lang][0][$val] = $value['mec_renewal_of_current_plan'];
  // Percentage of Employer Contribution.
  $node->field_mc_contrib_single[$lang][0][$val] = $value['mec_percentage_single'];
  $node->field_mc_contrib_family[$lang][0][$val] = $value['mec_percentage_family'];
  // Waiting Period for New Employees?
  $node->field_mc_waiting_period[$lang][0][$val] = $value['mec_waiting_period'];

  // Dental.
  // Current Carrier.
  $node->field_den_current_carrier[$lang][0][$val] = $value['den_current_carrier'];
  // Years with current carrier.
  $node->field_den_years_current_carrier[$lang][0][$val] = $value['den_years_with_current_carrier'];
  // Plan Year to Quote.
  $node->field_den_plan_start[$lang][0][$val] = $value['den_plan_year_to_quote_start'];
  $node->field_den_plan_end[$lang][0][$val] = $value['den_plan_year_to_quote_end'];
  // Is this a renewal of a current plan in BullsEye?
  $node->field_dn_renewal_current_plan_be[$lang][0][$val] = $value['den_renewal_of_current_plan'];
  // Percentage of Employer Contribution.
  $node->field_dn_contrib_single[$lang][0][$val] = $value['den_percentage_single'];
  $node->field_dn_contrib_family[$lang][0][$val] = $value['den_percentage_family'];
  // Waiting Period for New Employees?
  $node->field_dn_waiting_period[$lang][0][$val] = $value['den_waiting_period'];

  // Vision.
  // Current Carrier.
  $node->field_vs_current_carrier[$lang][0][$val] = $value['vs_current_carrier'];
  // Years with current carrier.
  $node->field_vs_years_current_carrier[$lang][0][$val] = $value['vs_years_with_current_carrier'];
  // Plan Year to Quote.
  $node->field_vs_plan_start[$lang][0][$val] = $value['vs_plan_year_to_quote_start'];
  $node->field_vs_plan_end[$lang][0][$val] = $value['vs_plan_year_to_quote_end'];
  // Is this a renewal of a current plan in BullsEye?
  $node->field_vs_renewal_current_plan_be[$lang][0][$val] = $value['vs_renewal_of_current_plan'];
  // Percentage of Employer Contribution.
  $node->field_vs_contrib_single[$lang][0][$val] = $value['vs_percentage_single'];
  $node->field_vs_contrib_family[$lang][0][$val] = $value['vs_percentage_family'];
  // Waiting Period for New Employees?
  $node->field_vs_waiting_period[$lang][0][$val] = $value['vs_waiting_period'];

  // Life.
  // Current Carrier.
  $node->field_lf_current_carrier[$lang][0][$val] = $value['lf_current_carrier'];
  // Years with current carrier.
  $node->field_lf_years_current_carrier[$lang][0][$val] = $value['lf_years_with_current_carrier'];
  // Plan Year to Quote.
  $node->field_lf_plan_start[$lang][0][$val] = $value['lf_plan_year_to_quote_start'];
  $node->field_lf_plan_end[$lang][0][$val] = $value['lf_plan_year_to_quote_end'];
  // Is this a renewal of a current plan in BullsEye?
  $node->field_lf_renewal_current_plan_be[$lang][0][$val] = $value['lf_renewal_of_current_plan'];
  // Percentage of Employer Contribution.
  $node->field_lf_contrib_single[$lang][0][$val] = $value['lf_percentage_single'];
  $node->field_lf_contrib_family[$lang][0][$val] = $value['lf_percentage_family'];
  // Waiting Period for New Employees?
  $node->field_lf_waiting_period[$lang][0][$val] = $value['lf_waiting_period'];

  // Short term disability.
  // Current Carrier.
  $node->field_std_current_carrier[$lang][0][$val] = $value['std_current_carrier'];
  // Years with current carrier.
  $node->field_std_years_current_carrier[$lang][0][$val] = $value['std_years_with_current_carrier'];
  // Plan Year to Quote.
  $node->field_std_plan_start[$lang][0][$val] = $value['std_plan_year_to_quote_start'];
  $node->field_std_plan_end[$lang][0][$val] = $value['std_plan_year_to_quote_end'];
  // Is this a renewal of a current plan in BullsEye?
  $node->field_sd_renewal_current_plan_be[$lang][0][$val] = $value['std_renewal_of_current_plan'];
  // Percentage of Employer Contribution.
  $node->field_sd_contrib_single[$lang][0][$val] = $value['std_percentage_single'];
  $node->field_sd_contrib_family[$lang][0][$val] = $value['std_percentage_family'];
  // Waiting Period for New Employees?
  $node->field_sd_waiting_period[$lang][0][$val] = $value['std_waiting_period'];

  // Retirement.
  // Current Carrier.
  $node->field_ret_current_carrier[$lang][0][$val] = $value['ret_current_carrier'];
  // Years with current carrier.
  $node->field_ret_years_current_carrier[$lang][0][$val] = $value['ret_years_with_current_carrier'];
  // Plan Year to Quote.
  $node->field_ret_plan_start[$lang][0][$val] = $value['ret_plan_year_to_quote_start'];
  $node->field_ret_plan_end[$lang][0][$val] = $value['ret_plan_year_to_quote_end'];
  // Is this a renewal of a current plan in BullsEye?
  $node->field_rt_renewal_current_plan_be[$lang][0][$val] = $value['ret_renewal_of_current_plan'];
  // Percentage of Employer Contribution.
  $node->field_rt_contrib_single[$lang][0][$val] = $value['ret_percentage_single'];
  $node->field_rt_contrib_family[$lang][0][$val] = $value['ret_percentage_family'];
  // Waiting Period for New Employees?
  $node->field_rt_waiting_period[$lang][0][$val] = $value['ret_waiting_period'];

  // Special Benefits.
  // Current Carrier.
  $node->field_sb_current_carrier[$lang][0][$val] = $value['sb_current_carrier'];
  // Years with current carrier.
  $node->field_sb_years_current_carrier[$lang][0][$val] = $value['sb_years_with_current_carrier'];
  // Plan Year to Quote.
  $node->field_sb_plan_start[$lang][0][$val] = $value['sb_plan_year_to_quote_start'];
  $node->field_sb_plan_end[$lang][0][$val] = $value['sb_plan_year_to_quote_end'];
  // Is this a renewal of a current plan in BullsEye?
  $node->field_sb_renewal_current_plan_be[$lang][0][$val] = $value['sb_renewal_of_current_plan'];
  // Percentage of Employer Contribution.
  $node->field_sb_contrib_single[$lang][0][$val] = $value['sb_percentage_single'];
  $node->field_sb_contrib_family[$lang][0][$val] = $value['sb_percentage_family'];
  // Waiting Period for New Employees?
  $node->field_sb_waiting_period[$lang][0][$val] = $value['sb_waiting_period'];

  /*************
   * Attachments.
   *************/
  if ($value['employee_census'] != 0) {
    $census_file = file_load($value['employee_census']);
    $census_file->display = 1;
    $census_file = file_copy($census_file, 'public://');
    $node->field_employee_census[$lang][0] = (array) $census_file;
  }
  if ($value['current_summary_of_benefit'] != 0) {
    $sb_file = file_load($value['current_summary_of_benefit']);
    $sb_file->display = 1;
    $sb_file = file_copy($sb_file, 'public://');
    $node->field_current_summary_of_benefit[$lang][0] = (array) $sb_file;
  }
  if ($value['current_bill'] != 0) {
    $cb_file = file_load($value['current_bill']);
    $cb_file->display = 1;
    $cb_file = file_copy($cb_file, 'public://');
    $node->field_current_bill[$lang][0] = (array) $cb_file;
  }
  if ($value['last_renewal_letter'] != 0) {
    $rl_file = file_load($value['last_renewal_letter']);
    $rl_file->display = 1;
    $rl_file = file_copy($rl_file, 'public://');
    $node->field_last_renewal_letter_rates[$lang][0] = (array) $rl_file;
  }
  if ($value['summary_of_monthly_claims_experience'] != 0) {
    $mce_file = file_load($value['summary_of_monthly_claims_experience']);
    $mce_file->display = 1;
    $mce_file = file_copy($mce_file, 'public://');
    $node->field_summary_monthly_claims[$lang][0] = (array) $mce_file;
  }
  if ($value['broker_of_record'] != 0) {
    $br_file = file_load($value['broker_of_record']);
    $br_file->display = 1;
    $br_file = file_copy($br_file, 'public://');
    $node->field_broker_of_record[$lang][0] = (array) $br_file;
  }
  if ($value['letter_of_authorization'] != 0) {
    $la_file = file_load($value['letter_of_authorization']);
    $la_file->display = 1;
    $la_file = file_copy($la_file, 'public://');
    $node->field_letter_of_authorization[$lang][0] = (array) $la_file;
  }
  if ($value['large_claims_report'] != 0) {
    $cr_file = file_load($value['large_claims_report']);
    $cr_file->display = 1;
    $cr_file = file_copy($cr_file, 'public://');
    $node->field_large_claims_report[$lang][0] = (array) $cr_file;
  }

  // Census Inclusions.
  if ($value['check_identifier'] == 1) {
    $node->field_census_must_inclusions[$lang][][$val] = 1;
  }
  if ($value['check_ssn'] == 1) {
    $node->field_census_must_inclusions[$lang][][$val] = 2;
  }
  if ($value['check_date_birth_age'] == 1) {
    $node->field_census_must_inclusions[$lang][][$val] = 3;
  }
  if ($value['check_gender'] == 1) {
    $node->field_census_must_inclusions[$lang][][$val] = 4;
  }
  if ($value['check_home_zip_codes'] == 1) {
    $node->field_census_must_inclusions[$lang][][$val] = 5;
  }
  if ($value['check_plan_selection'] == 1) {
    $node->field_census_must_inclusions[$lang][][$val] = 6;
  }
  if ($value['check_tier_levels'] == 1) {
    $node->field_census_must_inclusions[$lang][][$val] = 7;
  }
  if ($value['check_identification_of_retirees'] == 1) {
    $node->field_census_must_inclusions[$lang][][$val] = 8;
  }
  if ($value['check_identification_of_covered'] == 1) {
    $node->field_census_must_inclusions[$lang][][$val] = 9;
  }

  // Save the carrier in the storage.
  $node = node_submit($node);
  node_save($node);

  // Invalidate the existing cache to make sure that
  // the newly added one will get indexed too.
  cache_clear_all('rfp_listing', 'cache');

  // Create an activity.
  Bullseye::createSystemGeneratedActivity('rfp', $data['account_id']);


  if ($_GET['from_current_progress'] == 1) {

    // Set the account status to receive quote if
    // the link is form current progress.
    $wrapper = entity_metadata_wrapper('node', $data['account_id']);

    $action_status = $wrapper->field_action_status->value();
    $workflow_status = $wrapper->field_workflow_status->value();
    $account_status = $wrapper->field_account_status->value();

    if ($account_status == 'opportunity' && $workflow_status == 'rfp' && $action_status == 'generate_rfp') {
      $wrapper->field_action_status->set('receive_quote');
    }

    $wrapper->save();

    $alias = drupal_get_path_alias('node/' . $data['account_id']);
    $alias = substr($alias, 8);

    $param = array(
      'query' => array(
        'from' => 'opportunity',
        'from_rfp' => TRUE,
      )
    );

    // Redirect to company page to continue current progress activity.
    drupal_goto('company/' . $alias, $param);
  }
  else {
    // Reroute the page to the listing page.
    drupal_set_message(t('Successfully added RFP.'));
    drupal_goto('/rfps');
  }
}

/**
 * Implements hook_theme().
 */
function bullseye_rfp_theme($existing, $type, $theme, $path) {
  $items['benefit_pdf'] = array(
    'render element' => 'form',
    'template' => 'benefit-pdf',
    'path' => drupal_get_path('module', 'bullseye_rfp') . '/templates',
  );
  return $items;
}

/**
 * Generate the RFP PDF file.
 */
function bullseye_rfp_pdf_generate($benefit_title, $values, $form_values) {
  global $base_url, $user;
  $theme_directory = path_to_theme('theme', 'bullseye');

  $vars = array();

  // Initialize variables placeholder.
  $vars['company'] = '';
  $vars['email'] = '';
  $vars['phone'] = '';
  $vars['website'] = '';
  $vars['address'] = '';

  if (isset($_SESSION['add_rfp'])) {
    $data = $_SESSION['add_rfp'];
    $account = node_load($data['account_id']);

    // Contact.
    $fcid = $account->field_contacts[LANGUAGE_NONE][0]['value'];
    $contact = field_collection_item_load($fcid);

    $vars['company'] = $account->title;
    $vars['email'] = $contact->field_email[LANGUAGE_NONE][0]['value'];
    $vars['phone'] = $account->field_work_phone[LANGUAGE_NONE][0]['value'];
    $vars['website'] = $account->field_work_website[LANGUAGE_NONE][0]['value'];
    $street = $account->field_street[LANGUAGE_NONE][0]['value'];
    $city = $account->field_city[LANGUAGE_NONE][0]['value'];
    $state = $account->field_state_code[LANGUAGE_NONE][0]['value'];
    $code = $account->field_postal_code[LANGUAGE_NONE][0]['value'];
    $vars['address'] = $street . ', ' . $city . ', ' . $state . ' ' . $code;
  }

  $vars['benefit_name'] = $benefit_title;
  $vars['bootstrap_css'] = $base_url . '/' . $theme_directory . '/bootstrap/css/bootstrap.css';
  $vars['pdf_logo'] = $base_url . '/' . $theme_directory . '/images/archer-pdf-logo.png';

  $vars['fringe_rates'] = $form_values['fringe_rates'];
  $vars['proposed_effective_date'] = $form_values['proposed_effective_date'];
  $vars['other_work_locations'] = $form_values['other_work_locations'];
  $vars['number_of_employees'] = $form_values['number_of_employees'];
  $vars['number_of_dependents'] = $form_values['number_of_dependents'];
  $vars['nature_of_business'] = $form_values['nature_of_business'];
  $vars['years_in_business'] = $form_values['years_in_business'];
  $vars['tax_id'] = $form_values['tax_id'];
  $vars['renewal_date'] = $form_values['renewal_date'];

  $current_carrier = $values['current_carrier'] . ', ' . $values['years_with_current_carrier'];
  $plan_year_to_quote = $values['plan_year_to_quote_start'] . ' - ' . $values['plan_year_to_quote_end'];
  $vars['current_carrier'] = $current_carrier;
  $vars['plan_year_to_quote'] = $plan_year_to_quote;
  $vars['waiting_period'] = $values['waiting_period'];
  $vars['renewal'] = 'No';
  if ($values['renewal'] == 1) {
    $vars['renewal'] = 'Yes';
  }

  $html = theme('benefit_pdf', $vars);

  $filename = $benefit_title . '-' . date('mdYHis') . '-' . $user->uid . '-RFP.pdf';

  $pdf_data = array(
    'html' => $html,
    'filename' => $filename,
  );

  return $pdf_data;

}

/**
 * SUBMIT HANDLERS FOR RFP EMAIL.
 */


/**
 * Submit handler for generate_rfp_major_medical.
 */
function generate_rfp_major_medical($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['mm_current_carrier'];
  $vars['years_with_current_carrier'] = $values['mm_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['mm_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['mm_plan_year_to_quote_end'];
  $vars['renewal'] = $values['mm_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['mm_waiting_period'];

  if (isset($_SESSION['add_rfp'])) {
    $data = $_SESSION['add_rfp'];
    /*$account = node_load($data['account_id']);
    $fcid = $account->field_contacts[LANGUAGE_NONE][0]['value'];
    $contact = field_collection_item_load($fcid);
    $to = $contact->field_email[LANGUAGE_NONE][0]['value'];*/

    // Recipients.
    $recipients = array();
    if (is_array($values['mm_carrier_to_send_1'])) {
      $c1 = node_load($values['mm_carrier_to_send_1']['entity_id']);
      $recipients[] = $c1->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['mm_carrier_to_send_2'])) {
      $c2 = node_load($values['mm_carrier_to_send_2']['entity_id']);
      $recipients[] = $c2->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['mm_carrier_to_send_3'])) {
      $c3 = node_load($values['mm_carrier_to_send_3']['entity_id']);
      $recipients[] = $c3->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['mm_carrier_to_send_4'])) {
      $c4 = node_load($values['mm_carrier_to_send_4']['entity_id']);
      $recipients[] = $c4->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['mm_carrier_to_send_5'])) {
      $c5 = node_load($values['mm_carrier_to_send_5']['entity_id']);
      $recipients[] = $c5->field_email[LANGUAGE_NONE][0]['value'];
    }

    // Attachments.
    $attachments = array();
    if ($form_state['values']['major_medical_attach_ec'] == 1) {
      $attachments[] = file_load($values['employee_census']);
    }
    if ($form_state['values']['major_medical_attach_csob'] == 1) {
      $attachments[] = file_load($values['current_summary_of_benefit']);
    }
    if ($form_state['values']['major_medical_attach_cb'] == 1) {
      $attachments[] = file_load($values['current_bill']);
    }
    if ($form_state['values']['major_medical_attach_lrlr'] == 1) {
      $attachments[] = file_load($values['last_renewal_letter']);
    }
    if ($form_state['values']['major_medical_attach_somce'] == 1) {
      $attachments[] = file_load($values['summary_of_monthly_claims_experience']);
    }
    if ($form_state['values']['major_medical_attach_bor'] == 1) {
      $attachments[] = file_load($values['broker_of_record']);
    }
    if ($form_state['values']['major_medical_attach_loa'] == 1) {
      $attachments[] = file_load($values['letter_of_authorization']);
    }
    if ($form_state['values']['major_medical_attach_lcr'] == 1) {
      $attachments[] = file_load($values['large_claims_report']);
    }

    // Generate pdf and download it.
    // @TODO the function below is somehow preventing the email to execute.
    // Refactor this approach in the future.
    $pdf_data = bullseye_rfp_pdf_generate('Major Medical', $vars, $values);

    // Generate the PDF.
    $options = new Options();
    $options->set('isRemoteEnabled', TRUE);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($pdf_data['html']);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    // Saving pdf to server.
    $output = $dompdf->output();
    file_put_contents('public://' . $pdf_data['filename'], $output);

    // Send the email to specified recipients.
    foreach ($recipients as $to) {
      // Send the proposal via email.
      $params = array(
        'key' => 'bullseye',
        'to' => $to,
        'from' => $user->mail,
        'subject' => Bullseye::getRfpSubject(),
        'body' => $be->getRfpBody(),
        'attachments' => $attachments,
      );

      Bullseye::sendEmail($to, $user->mail, $params);
    }
    
  }
}

/**
 * Submit handler for generate_rfp_limited_medical.
 */
function generate_rfp_limited_medical($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['lm_current_carrier'];
  $vars['years_with_current_carrier'] = $values['lm_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['lm_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['lm_plan_year_to_quote_end'];
  $vars['renewal'] = $values['lm_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['lm_waiting_period'];

  if (isset($_SESSION['add_rfp'])) {
    $data = $_SESSION['add_rfp'];
    /*$account = node_load($data['account_id']);
    $fcid = $account->field_contacts[LANGUAGE_NONE][0]['value'];
    $contact = field_collection_item_load($fcid);
    $to = $contact->field_email[LANGUAGE_NONE][0]['value'];*/

    // Recipients.
    $recipients = array();
    if (is_array($values['lm_carrier_to_send_1'])) {
      $c1 = node_load($values['lm_carrier_to_send_1']['entity_id']);
      $recipients[] = $c1->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['lm_carrier_to_send_2'])) {
      $c2 = node_load($values['lm_carrier_to_send_2']['entity_id']);
      $recipients[] = $c2->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['lm_carrier_to_send_3'])) {
      $c3 = node_load($values['lm_carrier_to_send_3']['entity_id']);
      $recipients[] = $c3->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['lm_carrier_to_send_4'])) {
      $c4 = node_load($values['lm_carrier_to_send_4']['entity_id']);
      $recipients[] = $c4->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['lm_carrier_to_send_5'])) {
      $c5 = node_load($values['lm_carrier_to_send_5']['entity_id']);
      $recipients[] = $c5->field_email[LANGUAGE_NONE][0]['value'];
    }

    // Attachments.
    $attachments = array();
    if ($form_state['values']['limited_medical_attach_ec'] == 1) {
      $attachments[] = file_load($values['employee_census']);
    }
    if ($form_state['values']['limited_medical_attach_csob'] == 1) {
      $attachments[] = file_load($values['current_summary_of_benefit']);
    }
    if ($form_state['values']['limited_medical_attach_cb'] == 1) {
      $attachments[] = file_load($values['current_bill']);
    }
    if ($form_state['values']['limited_medical_attach_lrlr'] == 1) {
      $attachments[] = file_load($values['last_renewal_letter']);
    }
    if ($form_state['values']['limited_medical_attach_somce'] == 1) {
      $attachments[] = file_load($values['summary_of_monthly_claims_experience']);
    }
    if ($form_state['values']['limited_medical_attach_bor'] == 1) {
      $attachments[] = file_load($values['broker_of_record']);
    }
    if ($form_state['values']['limited_medical_attach_loa'] == 1) {
      $attachments[] = file_load($values['letter_of_authorization']);
    }
    if ($form_state['values']['limited_medical_attach_lcr'] == 1) {
      $attachments[] = file_load($values['large_claims_report']);
    }

    // Generate pdf and download it.
    // @TODO the function below is somehow preventing the email to execute.
    // Refactor this approach in the future.
    $pdf_data = bullseye_rfp_pdf_generate('Limited Medical', $vars, $values);

    // Generate the PDF.
    $options = new Options();
    $options->set('isRemoteEnabled', TRUE);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($pdf_data['html']);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    // Saving pdf to server.
    $output = $dompdf->output();
    file_put_contents('public://' . $pdf_data['filename'], $output);

    // Send the email to specified recipients.
    foreach ($recipients as $to) {
      // Send the proposal via email.
      $params = array(
        'key' => 'bullseye',
        'to' => $to,
        'from' => $user->mail,
        'subject' => Bullseye::getRfpSubject(),
        'body' => $be->getRfpBody(),
        'attachments' => $attachments,
      );

      Bullseye::sendEmail($to, $user->mail, $params);
    }

    
  }
}

/**
 * Submit handler for generate_rfp_teledoc.
 */
function generate_rfp_teledoc($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['tel_current_carrier'];
  $vars['years_with_current_carrier'] = $values['tel_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['tel_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['tel_plan_year_to_quote_end'];
  $vars['renewal'] = $values['tel_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['tel_waiting_period'];

  if (isset($_SESSION['add_rfp'])) {
    $data = $_SESSION['add_rfp'];
    /*$account = node_load($data['account_id']);
    $fcid = $account->field_contacts[LANGUAGE_NONE][0]['value'];
    $contact = field_collection_item_load($fcid);
    $to = $contact->field_email[LANGUAGE_NONE][0]['value'];*/

    // Recipients.
    $recipients = array();
    if (is_array($values['tel_carrier_to_send_1'])) {
      $c1 = node_load($values['tel_carrier_to_send_1']['entity_id']);
      $recipients[] = $c1->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['tel_carrier_to_send_2'])) {
      $c2 = node_load($values['tel_carrier_to_send_2']['entity_id']);
      $recipients[] = $c2->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['tel_carrier_to_send_3'])) {
      $c3 = node_load($values['tel_carrier_to_send_3']['entity_id']);
      $recipients[] = $c3->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['tel_carrier_to_send_4'])) {
      $c4 = node_load($values['tel_carrier_to_send_4']['entity_id']);
      $recipients[] = $c4->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['tel_carrier_to_send_5'])) {
      $c5 = node_load($values['tel_carrier_to_send_5']['entity_id']);
      $recipients[] = $c5->field_email[LANGUAGE_NONE][0]['value'];
    }

    // Attachments.
    $attachments = array();
    if ($form_state['values']['teledoc_attach_ec'] == 1) {
      $attachments[] = file_load($values['employee_census']);
    }
    if ($form_state['values']['teledoc_attach_csob'] == 1) {
      $attachments[] = file_load($values['current_summary_of_benefit']);
    }
    if ($form_state['values']['teledoc_attach_cb'] == 1) {
      $attachments[] = file_load($values['current_bill']);
    }
    if ($form_state['values']['teledoc_attach_lrlr'] == 1) {
      $attachments[] = file_load($values['last_renewal_letter']);
    }
    if ($form_state['values']['teledoc_attach_somce'] == 1) {
      $attachments[] = file_load($values['summary_of_monthly_claims_experience']);
    }
    if ($form_state['values']['teledoc_attach_bor'] == 1) {
      $attachments[] = file_load($values['broker_of_record']);
    }
    if ($form_state['values']['teledoc_attach_loa'] == 1) {
      $attachments[] = file_load($values['letter_of_authorization']);
    }
    if ($form_state['values']['teledoc_attach_lcr'] == 1) {
      $attachments[] = file_load($values['large_claims_report']);
    }

    // Generate pdf and download it.
    // @TODO the function below is somehow preventing the email to execute.
    // Refactor this approach in the future.
    $pdf_data = bullseye_rfp_pdf_generate('Telemedicine', $vars, $values);

    // Generate the PDF.
    $options = new Options();
    $options->set('isRemoteEnabled', TRUE);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($pdf_data['html']);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    // Saving pdf to server.
    $output = $dompdf->output();
    file_put_contents('public://' . $pdf_data['filename'], $output);

    // Send the email to specified recipients.
    foreach ($recipients as $to) {
      // Send the proposal via email.
      $params = array(
        'key' => 'bullseye',
        'to' => $to,
        'from' => $user->mail,
        'subject' => Bullseye::getRfpSubject(),
        'body' => $be->getRfpBody(),
        'attachments' => $attachments,
      );

      Bullseye::sendEmail($to, $user->mail, $params);
    }
  }
}

/**
 * Submit handler for generate_rfp_mec.
 */
function generate_rfp_mec($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['mec_current_carrier'];
  $vars['years_with_current_carrier'] = $values['mec_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['mec_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['mec_plan_year_to_quote_end'];
  $vars['renewal'] = $values['mec_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['mec_waiting_period'];

  if (isset($_SESSION['add_rfp'])) {
    $data = $_SESSION['add_rfp'];
    /*$account = node_load($data['account_id']);
    $fcid = $account->field_contacts[LANGUAGE_NONE][0]['value'];
    $contact = field_collection_item_load($fcid);
    $to = $contact->field_email[LANGUAGE_NONE][0]['value'];*/

    // Recipients.
    $recipients = array();
    if (is_array($values['mec_carrier_to_send_1'])) {
      $c1 = node_load($values['mec_carrier_to_send_1']['entity_id']);
      $recipients[] = $c1->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['mec_carrier_to_send_2'])) {
      $c2 = node_load($values['mec_carrier_to_send_2']['entity_id']);
      $recipients[] = $c2->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['mec_carrier_to_send_3'])) {
      $c3 = node_load($values['mec_carrier_to_send_3']['entity_id']);
      $recipients[] = $c3->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['mec_carrier_to_send_4'])) {
      $c4 = node_load($values['mec_carrier_to_send_4']['entity_id']);
      $recipients[] = $c4->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['mec_carrier_to_send_5'])) {
      $c5 = node_load($values['mec_carrier_to_send_5']['entity_id']);
      $recipients[] = $c5->field_email[LANGUAGE_NONE][0]['value'];
    }

    // Attachments.
    $attachments = array();
    if ($form_state['values']['mec_attach_ec'] == 1) {
      $attachments[] = file_load($values['employee_census']);
    }
    if ($form_state['values']['mec_attach_csob'] == 1) {
      $attachments[] = file_load($values['current_summary_of_benefit']);
    }
    if ($form_state['values']['mec_attach_cb'] == 1) {
      $attachments[] = file_load($values['current_bill']);
    }
    if ($form_state['values']['mec_attach_lrlr'] == 1) {
      $attachments[] = file_load($values['last_renewal_letter']);
    }
    if ($form_state['values']['mec_attach_somce'] == 1) {
      $attachments[] = file_load($values['summary_of_monthly_claims_experience']);
    }
    if ($form_state['values']['mec_attach_bor'] == 1) {
      $attachments[] = file_load($values['broker_of_record']);
    }
    if ($form_state['values']['mec_attach_loa'] == 1) {
      $attachments[] = file_load($values['letter_of_authorization']);
    }
    if ($form_state['values']['mec_attach_lcr'] == 1) {
      $attachments[] = file_load($values['large_claims_report']);
    }

    // Generate pdf and download it.
    // @TODO the function below is somehow preventing the email to execute.
    // Refactor this approach in the future.
    $pdf_data = bullseye_rfp_pdf_generate('MEC', $vars, $values);

    // Generate the PDF.
    $options = new Options();
    $options->set('isRemoteEnabled', TRUE);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($pdf_data['html']);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    // Saving pdf to server.
    $output = $dompdf->output();
    file_put_contents('public://' . $pdf_data['filename'], $output);

    // Send the email to specified recipients.
    foreach ($recipients as $to) {
      // Send the proposal via email.
      $params = array(
        'key' => 'bullseye',
        'to' => $to,
        'from' => $user->mail,
        'subject' => Bullseye::getRfpSubject(),
        'body' => $be->getRfpBody(),
        'attachments' => $attachments,
      );

      Bullseye::sendEmail($to, $user->mail, $params);
    }

  }
}

/**
 * Submit handler for generate_rfp_dental.
 */
function generate_rfp_dental($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['den_current_carrier'];
  $vars['years_with_current_carrier'] = $values['den_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['den_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['den_plan_year_to_quote_end'];
  $vars['renewal'] = $values['den_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['den_waiting_period'];

  if (isset($_SESSION['add_rfp'])) {
    $data = $_SESSION['add_rfp'];
    /*$account = node_load($data['account_id']);
    $fcid = $account->field_contacts[LANGUAGE_NONE][0]['value'];
    $contact = field_collection_item_load($fcid);
    $to = $contact->field_email[LANGUAGE_NONE][0]['value'];*/

    // Recipients.
    $recipients = array();
    if (is_array($values['den_carrier_to_send_1'])) {
      $c1 = node_load($values['den_carrier_to_send_1']['entity_id']);
      $recipients[] = $c1->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['den_carrier_to_send_2'])) {
      $c2 = node_load($values['den_carrier_to_send_2']['entity_id']);
      $recipients[] = $c2->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['den_carrier_to_send_3'])) {
      $c3 = node_load($values['den_carrier_to_send_3']['entity_id']);
      $recipients[] = $c3->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['den_carrier_to_send_4'])) {
      $c4 = node_load($values['den_carrier_to_send_4']['entity_id']);
      $recipients[] = $c4->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['den_carrier_to_send_5'])) {
      $c5 = node_load($values['den_carrier_to_send_5']['entity_id']);
      $recipients[] = $c5->field_email[LANGUAGE_NONE][0]['value'];
    }

    // Attachments.
    $attachments = array();
    if ($form_state['values']['dental_attach_ec'] == 1) {
      $attachments[] = file_load($values['employee_census']);
    }
    if ($form_state['values']['dental_attach_csob'] == 1) {
      $attachments[] = file_load($values['current_summary_of_benefit']);
    }
    if ($form_state['values']['dental_attach_cb'] == 1) {
      $attachments[] = file_load($values['current_bill']);
    }
    if ($form_state['values']['dental_attach_lrlr'] == 1) {
      $attachments[] = file_load($values['last_renewal_letter']);
    }
    if ($form_state['values']['dental_attach_somce'] == 1) {
      $attachments[] = file_load($values['summary_of_monthly_claims_experience']);
    }
    if ($form_state['values']['dental_attach_bor'] == 1) {
      $attachments[] = file_load($values['broker_of_record']);
    }
    if ($form_state['values']['dental_attach_loa'] == 1) {
      $attachments[] = file_load($values['letter_of_authorization']);
    }
    if ($form_state['values']['dental_attach_lcr'] == 1) {
      $attachments[] = file_load($values['large_claims_report']);
    }

    // Generate pdf and download it.
    // @TODO the function below is somehow preventing the email to execute.
    // Refactor this approach in the future.
    $pdf_data = bullseye_rfp_pdf_generate('Dental', $vars, $values);

    // Generate the PDF.
    $options = new Options();
    $options->set('isRemoteEnabled', TRUE);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($pdf_data['html']);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    // Saving pdf to server.
    $output = $dompdf->output();
    file_put_contents('public://' . $pdf_data['filename'], $output);

    // Send the email to specified recipients.
    foreach ($recipients as $to) {
      // Send the proposal via email.
      $params = array(
        'key' => 'bullseye',
        'to' => $to,
        'from' => $user->mail,
        'subject' => Bullseye::getRfpSubject(),
        'body' => $be->getRfpBody(),
        'attachments' => $attachments,
      );

      Bullseye::sendEmail($to, $user->mail, $params);
    }

  }
}

/**
 * Submit handler for generate_rfp_vision.
 */
function generate_rfp_vision($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['vs_current_carrier'];
  $vars['years_with_current_carrier'] = $values['vs_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['vs_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['vs_plan_year_to_quote_end'];
  $vars['renewal'] = $values['vs_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['vs_waiting_period'];

  if (isset($_SESSION['add_rfp'])) {
    $data = $_SESSION['add_rfp'];
    /*$account = node_load($data['account_id']);
    $fcid = $account->field_contacts[LANGUAGE_NONE][0]['value'];
    $contact = field_collection_item_load($fcid);
    $to = $contact->field_email[LANGUAGE_NONE][0]['value'];*/

    // Recipients.
    $recipients = array();
    if (is_array($values['vs_carrier_to_send_1'])) {
      $c1 = node_load($values['vs_carrier_to_send_1']['entity_id']);
      $recipients[] = $c1->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['vs_carrier_to_send_2'])) {
      $c2 = node_load($values['vs_carrier_to_send_2']['entity_id']);
      $recipients[] = $c2->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['vs_carrier_to_send_3'])) {
      $c3 = node_load($values['vs_carrier_to_send_3']['entity_id']);
      $recipients[] = $c3->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['vs_carrier_to_send_4'])) {
      $c4 = node_load($values['vs_carrier_to_send_4']['entity_id']);
      $recipients[] = $c4->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['vs_carrier_to_send_5'])) {
      $c5 = node_load($values['vs_carrier_to_send_5']['entity_id']);
      $recipients[] = $c5->field_email[LANGUAGE_NONE][0]['value'];
    }

    // Attachments.
    $attachments = array();
    if ($form_state['values']['vision_attach_ec'] == 1) {
      $attachments[] = file_load($values['employee_census']);
    }
    if ($form_state['values']['vision_attach_csob'] == 1) {
      $attachments[] = file_load($values['current_summary_of_benefit']);
    }
    if ($form_state['values']['vision_attach_cb'] == 1) {
      $attachments[] = file_load($values['current_bill']);
    }
    if ($form_state['values']['vision_attach_lrlr'] == 1) {
      $attachments[] = file_load($values['last_renewal_letter']);
    }
    if ($form_state['values']['vision_attach_somce'] == 1) {
      $attachments[] = file_load($values['summary_of_monthly_claims_experience']);
    }
    if ($form_state['values']['vision_attach_bor'] == 1) {
      $attachments[] = file_load($values['broker_of_record']);
    }
    if ($form_state['values']['vision_attach_loa'] == 1) {
      $attachments[] = file_load($values['letter_of_authorization']);
    }
    if ($form_state['values']['vision_attach_lcr'] == 1) {
      $attachments[] = file_load($values['large_claims_report']);
    }

    // Generate pdf and download it.
    // @TODO the function below is somehow preventing the email to execute.
    // Refactor this approach in the future.
    $pdf_data = bullseye_rfp_pdf_generate('Vision', $vars, $values);

    // Generate the PDF.
    $options = new Options();
    $options->set('isRemoteEnabled', TRUE);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($pdf_data['html']);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    // Saving pdf to server.
    $output = $dompdf->output();
    file_put_contents('public://' . $pdf_data['filename'], $output);

    // Send the email to specified recipients.
    foreach ($recipients as $to) {
      // Send the proposal via email.
      $params = array(
        'key' => 'bullseye',
        'to' => $to,
        'from' => $user->mail,
        'subject' => Bullseye::getRfpSubject(),
        'body' => $be->getRfpBody(),
        'attachments' => $attachments,
      );

      Bullseye::sendEmail($to, $user->mail, $params);
    }

  }
}

/**
 * Submit handler for generate_rfp_life.
 */
function generate_rfp_life($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['lf_current_carrier'];
  $vars['years_with_current_carrier'] = $values['lf_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['lf_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['lf_plan_year_to_quote_end'];
  $vars['renewal'] = $values['lf_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['lf_waiting_period'];

  if (isset($_SESSION['add_rfp'])) {
    $data = $_SESSION['add_rfp'];
    /*$account = node_load($data['account_id']);
    $fcid = $account->field_contacts[LANGUAGE_NONE][0]['value'];
    $contact = field_collection_item_load($fcid);
    $to = $contact->field_email[LANGUAGE_NONE][0]['value'];*/

    // Recipients.
    $recipients = array();
    if (is_array($values['lf_carrier_to_send_1'])) {
      $c1 = node_load($values['lf_carrier_to_send_1']['entity_id']);
      $recipients[] = $c1->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['lf_carrier_to_send_2'])) {
      $c2 = node_load($values['lf_carrier_to_send_2']['entity_id']);
      $recipients[] = $c2->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['lf_carrier_to_send_3'])) {
      $c3 = node_load($values['lf_carrier_to_send_3']['entity_id']);
      $recipients[] = $c3->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['lf_carrier_to_send_4'])) {
      $c4 = node_load($values['lf_carrier_to_send_4']['entity_id']);
      $recipients[] = $c4->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['lf_carrier_to_send_5'])) {
      $c5 = node_load($values['lf_carrier_to_send_5']['entity_id']);
      $recipients[] = $c5->field_email[LANGUAGE_NONE][0]['value'];
    }

    // Attachments.
    $attachments = array();
    if ($form_state['values']['life_attach_ec'] == 1) {
      $attachments[] = file_load($values['employee_census']);
    }
    if ($form_state['values']['life_attach_csob'] == 1) {
      $attachments[] = file_load($values['current_summary_of_benefit']);
    }
    if ($form_state['values']['life_attach_cb'] == 1) {
      $attachments[] = file_load($values['current_bill']);
    }
    if ($form_state['values']['life_attach_lrlr'] == 1) {
      $attachments[] = file_load($values['last_renewal_letter']);
    }
    if ($form_state['values']['life_attach_somce'] == 1) {
      $attachments[] = file_load($values['summary_of_monthly_claims_experience']);
    }
    if ($form_state['values']['life_attach_bor'] == 1) {
      $attachments[] = file_load($values['broker_of_record']);
    }
    if ($form_state['values']['life_attach_loa'] == 1) {
      $attachments[] = file_load($values['letter_of_authorization']);
    }
    if ($form_state['values']['life_attach_lcr'] == 1) {
      $attachments[] = file_load($values['large_claims_report']);
    }

    // Generate pdf and download it.
    // @TODO the function below is somehow preventing the email to execute.
    // Refactor this approach in the future.
    $pdf_data = bullseye_rfp_pdf_generate('Life & AD&D', $vars, $values);

    // Generate the PDF.
    $options = new Options();
    $options->set('isRemoteEnabled', TRUE);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($pdf_data['html']);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    // Saving pdf to server.
    $output = $dompdf->output();
    file_put_contents('public://' . $pdf_data['filename'], $output);

    // Send the email to specified recipients.
    foreach ($recipients as $to) {
      // Send the proposal via email.
      $params = array(
        'key' => 'bullseye',
        'to' => $to,
        'from' => $user->mail,
        'subject' => Bullseye::getRfpSubject(),
        'body' => $be->getRfpBody(),
        'attachments' => $attachments,
      );

      Bullseye::sendEmail($to, $user->mail, $params);
    }
  }
}

/**
 * Submit handler for generate_rfp_short_term_disability.
 */
function generate_rfp_short_term_disability($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['std_current_carrier'];
  $vars['years_with_current_carrier'] = $values['std_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['std_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['std_plan_year_to_quote_end'];
  $vars['renewal'] = $values['std_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['std_waiting_period'];

  if (isset($_SESSION['add_rfp'])) {
    $data = $_SESSION['add_rfp'];
    /*$account = node_load($data['account_id']);
    $fcid = $account->field_contacts[LANGUAGE_NONE][0]['value'];
    $contact = field_collection_item_load($fcid);
    $to = $contact->field_email[LANGUAGE_NONE][0]['value'];*/

    // Recipients.
    $recipients = array();
    if (is_array($values['std_carrier_to_send_1'])) {
      $c1 = node_load($values['std_carrier_to_send_1']['entity_id']);
      $recipients[] = $c1->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['std_carrier_to_send_2'])) {
      $c2 = node_load($values['std_carrier_to_send_2']['entity_id']);
      $recipients[] = $c2->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['std_carrier_to_send_3'])) {
      $c3 = node_load($values['std_carrier_to_send_3']['entity_id']);
      $recipients[] = $c3->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['std_carrier_to_send_4'])) {
      $c4 = node_load($values['std_carrier_to_send_4']['entity_id']);
      $recipients[] = $c4->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['std_carrier_to_send_5'])) {
      $c5 = node_load($values['std_carrier_to_send_5']['entity_id']);
      $recipients[] = $c5->field_email[LANGUAGE_NONE][0]['value'];
    }

    // Attachments.
    $attachments = array();
    if ($form_state['values']['short_term_disability_attach_ec'] == 1) {
      $attachments[] = file_load($values['employee_census']);
    }
    if ($form_state['values']['short_term_disability_attach_csob'] == 1) {
      $attachments[] = file_load($values['current_summary_of_benefit']);
    }
    if ($form_state['values']['short_term_disability_attach_cb'] == 1) {
      $attachments[] = file_load($values['current_bill']);
    }
    if ($form_state['values']['short_term_disability_attach_lrlr'] == 1) {
      $attachments[] = file_load($values['last_renewal_letter']);
    }
    if ($form_state['values']['short_term_disability_attach_somce'] == 1) {
      $attachments[] = file_load($values['summary_of_monthly_claims_experience']);
    }
    if ($form_state['values']['short_term_disability_attach_bor'] == 1) {
      $attachments[] = file_load($values['broker_of_record']);
    }
    if ($form_state['values']['short_term_disability_attach_loa'] == 1) {
      $attachments[] = file_load($values['letter_of_authorization']);
    }
    if ($form_state['values']['short_term_disability_attach_lcr'] == 1) {
      $attachments[] = file_load($values['large_claims_report']);
    }

    // Generate pdf and download it.
    // @TODO the function below is somehow preventing the email to execute.
    // Refactor this approach in the future.
    $pdf_data = bullseye_rfp_pdf_generate('Short Term Disability', $vars, $values);

    // Generate the PDF.
    $options = new Options();
    $options->set('isRemoteEnabled', TRUE);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($pdf_data['html']);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    // Saving pdf to server.
    $output = $dompdf->output();
    file_put_contents('public://' . $pdf_data['filename'], $output);

    // Send the email to specified recipients.
    foreach ($recipients as $to) {
      // Send the proposal via email.
      $params = array(
        'key' => 'bullseye',
        'to' => $to,
        'from' => $user->mail,
        'subject' => Bullseye::getRfpSubject(),
        'body' => $be->getRfpBody(),
        'attachments' => $attachments,
      );

      Bullseye::sendEmail($to, $user->mail, $params);
    }
    
  }
}

/**
 * Submit handler for generate_rfp_retirement.
 */
function generate_rfp_retirement($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['ret_current_carrier'];
  $vars['years_with_current_carrier'] = $values['ret_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['ret_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['ret_plan_year_to_quote_end'];
  $vars['renewal'] = $values['ret_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['ret_waiting_period'];

  if (isset($_SESSION['add_rfp'])) {
    $data = $_SESSION['add_rfp'];
    /*$account = node_load($data['account_id']);
    $fcid = $account->field_contacts[LANGUAGE_NONE][0]['value'];
    $contact = field_collection_item_load($fcid);
    $to = $contact->field_email[LANGUAGE_NONE][0]['value'];*/

    // Recipients.
    $recipients = array();
    if (is_array($values['ret_carrier_to_send_1'])) {
      $c1 = node_load($values['ret_carrier_to_send_1']['entity_id']);
      $recipients[] = $c1->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['ret_carrier_to_send_2'])) {
      $c2 = node_load($values['ret_carrier_to_send_2']['entity_id']);
      $recipients[] = $c2->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['ret_carrier_to_send_3'])) {
      $c3 = node_load($values['ret_carrier_to_send_3']['entity_id']);
      $recipients[] = $c3->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['ret_carrier_to_send_4'])) {
      $c4 = node_load($values['ret_carrier_to_send_4']['entity_id']);
      $recipients[] = $c4->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['ret_carrier_to_send_5'])) {
      $c5 = node_load($values['ret_carrier_to_send_5']['entity_id']);
      $recipients[] = $c5->field_email[LANGUAGE_NONE][0]['value'];
    }

    // Attachments.
    $attachments = array();
    if ($form_state['values']['retirement_attach_ec'] == 1) {
      $attachments[] = file_load($values['employee_census']);
    }
    if ($form_state['values']['retirement_attach_csob'] == 1) {
      $attachments[] = file_load($values['current_summary_of_benefit']);
    }
    if ($form_state['values']['retirement_attach_cb'] == 1) {
      $attachments[] = file_load($values['current_bill']);
    }
    if ($form_state['values']['retirement_attach_lrlr'] == 1) {
      $attachments[] = file_load($values['last_renewal_letter']);
    }
    if ($form_state['values']['retirement_attach_somce'] == 1) {
      $attachments[] = file_load($values['summary_of_monthly_claims_experience']);
    }
    if ($form_state['values']['retirement_attach_bor'] == 1) {
      $attachments[] = file_load($values['broker_of_record']);
    }
    if ($form_state['values']['retirement_attach_loa'] == 1) {
      $attachments[] = file_load($values['letter_of_authorization']);
    }
    if ($form_state['values']['retirement_attach_lcr'] == 1) {
      $attachments[] = file_load($values['large_claims_report']);
    }

    // Generate pdf and download it.
    // @TODO the function below is somehow preventing the email to execute.
    // Refactor this approach in the future.
    $pdf_data = bullseye_rfp_pdf_generate('Retirement', $vars, $values);

    // Generate the PDF.
    $options = new Options();
    $options->set('isRemoteEnabled', TRUE);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($pdf_data['html']);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    // Saving pdf to server.
    $output = $dompdf->output();
    file_put_contents('public://' . $pdf_data['filename'], $output);

    // Send the email to specified recipients.
    foreach ($recipients as $to) {
      // Send the proposal via email.
      $params = array(
        'key' => 'bullseye',
        'to' => $to,
        'from' => $user->mail,
        'subject' => Bullseye::getRfpSubject(),
        'body' => $be->getRfpBody(),
        'attachments' => $attachments,
      );

      Bullseye::sendEmail($to, $user->mail, $params);
    }

  }
}

/**
 * Submit handler for generate_rfp_special_benefits.
 */
function generate_rfp_special_benefits($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['sb_current_carrier'];
  $vars['years_with_current_carrier'] = $values['sb_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['sb_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['sb_plan_year_to_quote_end'];
  $vars['renewal'] = $values['sb_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['sb_waiting_period'];

  if (isset($_SESSION['add_rfp'])) {
    $data = $_SESSION['add_rfp'];
    /*$account = node_load($data['account_id']);
    $fcid = $account->field_contacts[LANGUAGE_NONE][0]['value'];
    $contact = field_collection_item_load($fcid);
    $to = $contact->field_email[LANGUAGE_NONE][0]['value'];*/

    // Recipients.
    $recipients = array();
    if (is_array($values['sb_carrier_to_send_1'])) {
      $c1 = node_load($values['sb_carrier_to_send_1']['entity_id']);
      $recipients[] = $c1->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['sb_carrier_to_send_2'])) {
      $c2 = node_load($values['sb_carrier_to_send_2']['entity_id']);
      $recipients[] = $c2->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['sb_carrier_to_send_3'])) {
      $c3 = node_load($values['sb_carrier_to_send_3']['entity_id']);
      $recipients[] = $c3->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['sb_carrier_to_send_4'])) {
      $c4 = node_load($values['sb_carrier_to_send_4']['entity_id']);
      $recipients[] = $c4->field_email[LANGUAGE_NONE][0]['value'];
    }
    if (is_array($values['sb_carrier_to_send_5'])) {
      $c5 = node_load($values['sb_carrier_to_send_5']['entity_id']);
      $recipients[] = $c5->field_email[LANGUAGE_NONE][0]['value'];
    }

    // Attachments.
    $attachments = array();
    if ($values['special_benefits_attach_ec'] == 1) {
      $attachments[] = file_load($values['employee_census']);
    }
    if ($values['special_benefits_attach_csob'] == 1) {
      $attachments[] = file_load($values['current_summary_of_benefit']);
    }
    if ($values['special_benefits_attach_cb'] == 1) {
       $attachments[] = file_load($values['current_bill']);
    }
    if ($values['special_benefits_attach_lrlr'] == 1) {
       $attachments[] = file_load($values['last_renewal_letter']);
    }
    if ($values['special_benefits_attach_somce'] == 1) {
       $attachments[] = file_load($values['summary_of_monthly_claims_experience']);
    }
    if ($values['special_benefits_attach_bor'] == 1) {
       $attachments[] = file_load($values['broker_of_record']);
    }
    if ($values['special_benefits_attach_loa'] == 1) {
       $attachments[] = file_load($values['letter_of_authorization']);
    }
    if ($values['special_benefits_attach_lcr'] == 1) {
       $attachments[] = file_load($values['large_claims_report']);
    }

    // Generate pdf and download it.
    // @TODO the function below is somehow preventing the email to execute.
    // Refactor this approach in the future.
    $pdf_data = bullseye_rfp_pdf_generate('Special Benefits', $vars, $values);

    // Generate the PDF.
    $options = new Options();
    $options->set('isRemoteEnabled', TRUE);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($pdf_data['html']);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    // Saving pdf to server.
    $output = $dompdf->output();
    file_put_contents('public://' . $pdf_data['filename'], $output);

    // Send the email to specified recipients.
    foreach ($recipients as $to) {
      // Send the proposal via email.
      $params = array(
        'key' => 'bullseye',
        'to' => $to,
        'from' => $user->mail,
        'subject' => Bullseye::getRfpSubject(),
        'body' => $be->getRfpBody(),
        'attachments' => $attachments,
      );

      Bullseye::sendEmail($to, $user->mail, $params);
    }
  }
}


/**
 * SUBMIT HANDLERS FOR RFP DOWNLOAD.
 */

/**
 * Submit handler for generate_rfp_major_medical_dl.
 */
function generate_rfp_major_medical_dl($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['mm_current_carrier'];
  $vars['years_with_current_carrier'] = $values['mm_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['mm_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['mm_plan_year_to_quote_end'];
  $vars['renewal'] = $values['mm_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['mm_waiting_period'];

  // Generate pdf and download it.
  $pdf_data = bullseye_rfp_pdf_generate('Major Medical', $vars, $values);

  // Generate the PDF.
  $options = new Options();
  $options->set('isRemoteEnabled', TRUE);
  $dompdf = new Dompdf($options);
  $dompdf->loadHtml($pdf_data['html']);
  $dompdf->setPaper('A4', 'portrait');
  $dompdf->render();
  $dompdf->stream($pdf_data['filename']);

}

/**
 * Submit handler for generate_rfp_limited_medical_dl.
 */
function generate_rfp_limited_medical_dl($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['lm_current_carrier'];
  $vars['years_with_current_carrier'] = $values['lm_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['lm_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['lm_plan_year_to_quote_end'];
  $vars['renewal'] = $values['lm_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['lm_waiting_period'];

  $pdf_data = bullseye_rfp_pdf_generate('Limited Medical', $vars, $values);

  // Generate the PDF.
  $options = new Options();
  $options->set('isRemoteEnabled', TRUE);
  $dompdf = new Dompdf($options);
  $dompdf->loadHtml($pdf_data['html']);
  $dompdf->setPaper('A4', 'portrait');
  $dompdf->render();
  $dompdf->stream($pdf_data['filename']);
}

/**
 * Submit handler for generate_rfp_teledoc_dl.
 */
function generate_rfp_teledoc_dl($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['tel_current_carrier'];
  $vars['years_with_current_carrier'] = $values['tel_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['tel_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['tel_plan_year_to_quote_end'];
  $vars['renewal'] = $values['tel_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['tel_waiting_period'];

  $pdf_data = bullseye_rfp_pdf_generate('Telemedicine', $vars, $values);

  // Generate the PDF.
  $options = new Options();
  $options->set('isRemoteEnabled', TRUE);
  $dompdf = new Dompdf($options);
  $dompdf->loadHtml($pdf_data['html']);
  $dompdf->setPaper('A4', 'portrait');
  $dompdf->render();
  $dompdf->stream($pdf_data['filename']);

}

/**
 * Submit handler for generate_rfp_mec_dl.
 */
function generate_rfp_mec_dl($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['mec_current_carrier'];
  $vars['years_with_current_carrier'] = $values['mec_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['mec_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['mec_plan_year_to_quote_end'];
  $vars['renewal'] = $values['mec_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['mec_waiting_period'];

  $pdf_data = bullseye_rfp_pdf_generate('MEC', $vars, $values);

  // Generate the PDF.
  $options = new Options();
  $options->set('isRemoteEnabled', TRUE);
  $dompdf = new Dompdf($options);
  $dompdf->loadHtml($pdf_data['html']);
  $dompdf->setPaper('A4', 'portrait');
  $dompdf->render();
  $dompdf->stream($pdf_data['filename']);

}

/**
 * Submit handler for generate_rfp_dental_dl.
 */
function generate_rfp_dental_dl($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['den_current_carrier'];
  $vars['years_with_current_carrier'] = $values['den_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['den_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['den_plan_year_to_quote_end'];
  $vars['renewal'] = $values['den_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['den_waiting_period'];

  $pdf_data = bullseye_rfp_pdf_generate('Dental', $vars, $values);

  // Generate the PDF.
  $options = new Options();
  $options->set('isRemoteEnabled', TRUE);
  $dompdf = new Dompdf($options);
  $dompdf->loadHtml($pdf_data['html']);
  $dompdf->setPaper('A4', 'portrait');
  $dompdf->render();
  $dompdf->stream($pdf_data['filename']);
}

/**
 * Submit handler for generate_rfp_vision_dl.
 */
function generate_rfp_vision_dl($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['vs_current_carrier'];
  $vars['years_with_current_carrier'] = $values['vs_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['vs_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['vs_plan_year_to_quote_end'];
  $vars['renewal'] = $values['vs_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['vs_waiting_period'];

  $pdf_data = bullseye_rfp_pdf_generate('Vision', $vars, $values);

  // Generate the PDF.
  $options = new Options();
  $options->set('isRemoteEnabled', TRUE);
  $dompdf = new Dompdf($options);
  $dompdf->loadHtml($pdf_data['html']);
  $dompdf->setPaper('A4', 'portrait');
  $dompdf->render();
  $dompdf->stream($pdf_data['filename']);

}

/**
 * Submit handler for generate_rfp_life_dl.
 */
function generate_rfp_life_dl($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['lf_current_carrier'];
  $vars['years_with_current_carrier'] = $values['lf_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['lf_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['lf_plan_year_to_quote_end'];
  $vars['renewal'] = $values['lf_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['lf_waiting_period'];

  $pdf_data = bullseye_rfp_pdf_generate('Life & AD&D', $vars, $values);

  // Generate the PDF.
  $options = new Options();
  $options->set('isRemoteEnabled', TRUE);
  $dompdf = new Dompdf($options);
  $dompdf->loadHtml($pdf_data['html']);
  $dompdf->setPaper('A4', 'portrait');
  $dompdf->render();
  $dompdf->stream($pdf_data['filename']);

}

/**
 * Submit handler for generate_rfp_short_term_disability_dl.
 */
function generate_rfp_short_term_disability_dl($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['std_current_carrier'];
  $vars['years_with_current_carrier'] = $values['std_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['std_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['std_plan_year_to_quote_end'];
  $vars['renewal'] = $values['std_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['std_waiting_period'];

  $pdf_data = bullseye_rfp_pdf_generate('Short Term Disability', $vars, $values);

  // Generate the PDF.
  $options = new Options();
  $options->set('isRemoteEnabled', TRUE);
  $dompdf = new Dompdf($options);
  $dompdf->loadHtml($pdf_data['html']);
  $dompdf->setPaper('A4', 'portrait');
  $dompdf->render();
  $dompdf->stream($pdf_data['filename']);

}

/**
 * Submit handler for generate_rfp_retirement_dl.
 */
function generate_rfp_retirement_dl($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['ret_current_carrier'];
  $vars['years_with_current_carrier'] = $values['ret_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['ret_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['ret_plan_year_to_quote_end'];
  $vars['renewal'] = $values['ret_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['ret_waiting_period'];

  $pdf_data = bullseye_rfp_pdf_generate('Retirement', $vars, $values);

  // Generate the PDF.
  $options = new Options();
  $options->set('isRemoteEnabled', TRUE);
  $dompdf = new Dompdf($options);
  $dompdf->loadHtml($pdf_data['html']);
  $dompdf->setPaper('A4', 'portrait');
  $dompdf->render();
  $dompdf->stream($pdf_data['filename']);

}

/**
 * Submit handler for generate_rfp_special_benefits_dl.
 */
function generate_rfp_special_benefits_dl($form, &$form_state) {
  global $user;

  $values = $form_state['values'];

  $be = new Bullseye($user);

  $form_state['rebuild'] = TRUE;
  $vars = array();
  $vars['current_carrier'] = $values['sb_current_carrier'];
  $vars['years_with_current_carrier'] = $values['sb_years_with_current_carrier'];
  $vars['plan_year_to_quote_start'] = $values['sb_plan_year_to_quote_start'];
  $vars['plan_year_to_quote_end'] = $values['sb_plan_year_to_quote_end'];
  $vars['renewal'] = $values['sb_renewal_of_current_plan'];
  $vars['waiting_period'] = $values['sb_waiting_period'];

  $pdf_data = bullseye_rfp_pdf_generate('Special Benefits', $vars, $values);

  // Generate the PDF.
  $options = new Options();
  $options->set('isRemoteEnabled', TRUE);
  $dompdf = new Dompdf($options);
  $dompdf->loadHtml($pdf_data['html']);
  $dompdf->setPaper('A4', 'portrait');
  $dompdf->render();
  $dompdf->stream($pdf_data['filename']);

}
