<?php
/**
 * RFP module file.
 *
 * @author
 *  Gerald Villorente
 */
/**
 * Implements hook_menu().
 */
function bullseye_rfp_menu() {
  $items = array();

  $items['rfps/add'] = array(
    'title' => 'Create New RFP',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bullseye_rfp_form'),
    'access arguments' => array('add rfp'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['rfps/initial-add'] = array(
    'title' => 'Create New RFP',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bullseye_rfp_initial_add_form'),
    'access arguments' => array('add rfp'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function bullseye_rfp_permission() {
  return array(
    'add rfp' => array(
      'title' => t('Create new RFP'),
      'description' => t('Allow user to add new rfp.'),
    ),
  );
}

/**
 * Implements hook_form().
 *
 * Add RFP form (initial form popup).
 */
function bullseye_rfp_initial_add_form($form, &$form_state) {

  $form = array();

  $form['#attributes']['class'][] = 'be-forms be-forms-custom';

  $form['form_title'] = array(
    '#prefix' => '<div class="form-title">',
    '#suffix' => '</div>',
    '#markup' => '<h2>' . t('Create New RFP') . '</h2>',
  );

  $form['account'] = array(
    '#required' => FALSE,
    '#type' => 'entityreference',
    '#title' => t('Select Account'),
    '#era_entity_type' => 'node',
    '#era_bundles' => array('accounts'),
    '#era_cardinality' => 1,
    '#era_query_settings' => array(
      'limit' => 15, // Default is 50.
      'property_conditions' => array(
        array('status', 1, '='),
      ),
      'field_conditions' => array(),
    ),
  );

  $form['benefits_container'] = array(
    '#type' => 'container',
    'benefits' => array(),
  );

  $form['benefits_container']['benefits']['major_medical'] = array(
    '#type' => 'checkbox',
    '#title' => t('Major Medical'),
  );

  $form['benefits_container']['benefits']['limited_medical'] = array(
    '#type' => 'checkbox',
    '#title' => t('Limited Medical'),
  );

  $form['benefits_container']['benefits']['teledoc'] = array(
    '#type' => 'checkbox',
    '#title' => t('Telemedicine'),
  );

  $form['benefits_container']['benefits']['mec'] = array(
    '#type' => 'checkbox',
    '#title' => t('MEC'),
  );

  $form['benefits_container']['benefits']['life'] = array(
    '#type' => 'checkbox',
    '#title' => t('Life & AD&D'),
  );

  $form['benefits_container']['benefits']['short_term_disability'] = array(
    '#type' => 'checkbox',
    '#title' => t('Short Term Disability'),
  );

  $form['benefits_container']['benefits']['dental'] = array(
    '#type' => 'checkbox',
    '#title' => t('Dental'),
  );

  $form['benefits_container']['benefits']['vision'] = array(
    '#type' => 'checkbox',
    '#title' => t('Vision'),
  );

  $form['benefits_container']['benefits']['retirement'] = array(
    '#type' => 'checkbox',
    '#title' => t('Retirement'),
  );

  $form['benefits_container']['benefits']['special_benefits'] = array(
    '#type' => 'checkbox',
    '#title' => t('Special Benefits'),
  );

  $form['special_benefits_text'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Enter special benefit'),
    ),
  );

  $form['submit_container'] = array(
    '#type' => 'container',
  );

  $form['submit_container']['cancel'] = array(
    '#markup' => '<a class="gray-btn" href="/" onClick="parent.Lightbox.end();">Cancel</a>',
  );

  $form['submit_container']['submit'] = array(
    '#type' => 'submit',
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
    '#value' => t('Next'),
  );

  return $form;
}

/**
 * Form submit for initial create RFP Form.
 */
function bullseye_rfp_initial_add_form_submit($form, &$form_state) {
  // Clear session first.
  unset($_SESSION['add_rfp']);

  $account = node_load($form_state['values']['account']['entity_id']);
  $query = '/rfps/add?';
  $query .= 'account_name=' . $account->field_company[LANGUAGE_NONE][0]['value'];

  // Save the data temporarily to session variable.
  $_SESSION['add_rfp'] = array(
    'account_id' => $form_state['values']['account']['entity_id'],
    'major_medical' => $form_state['values']['major_medical'],
    'limited_medical' => $form_state['values']['limited_medical'],
    'teledoc' => $form_state['values']['teledoc'],
    'mec' => $form_state['values']['mec'],
    'life' => $form_state['values']['life'],
    'short_term_disability' => $form_state['values']['short_term_disability'],
    'dental' => $form_state['values']['dental'],
    'vision' => $form_state['values']['vision'],
    'retirement' => $form_state['values']['retirement'],
    'special_benefits' => $form_state['values']['special_benefits'],
    'special_benefits_text' => $form_state['values']['special_benefits_text'],
  );

  $benefits = array();

  // Prepare benefits data before passing to url parameter.
  foreach ($form_state['complete form']['benefits_container']['benefits'] as $key => $value) {
    if ($key[0] != '#') {
      $benefits[$key] = $value['#value'];
    }
  }

  // Build the parameter query for benefits array.
  $benefits_query = http_build_query(array('benefits' => $benefits));
  $query .= '&' . $benefits_query;

  // Close the lightbox and redirect to the next create new RFP page.
  print '<script>parent.location = "' . $query . '";</script>';
  print '<script>parent.Lightbox.end();</script>';
  die();
}

/**
 * Implements hook_form().
 *
 * Add RFP form.
 */
function bullseye_rfp_form($form, &$form_state) {
  $form = array();

  $form['#attributes']['class'][] = 'be-forms be-forms-custom';

  // Fringe Rate/s.
  $form['fringe_rates'] = array(
    '#type' => 'textfield',
    '#title' => t('Fringe Rate/s'),
    '#attributes' => array(
      'placeholder' => '500',
    ),
  );

  // Proposed Effective Date.
  $form['proposed_effective_date'] = array(
    '#type' => 'date_popup',
    '#date_format' => 'm/d/Y',
    '#default_value' => 'YYYY-MM-DD',
    '#date_year_range' => '0:+3',
    '#title' => t('Proposed Effective Date'),
  );

  // Other Work Locations and Zip Codes.
  $form['other_work_locations'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Work Locations and Zip Codes'),
    '#attributes' => array(
      'placeholder' => 'Dallas 88829, New Jersey 81920',
    ),
  );

  // Number of Employees.
  $form['number_of_employees'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Employees'),
    '#attributes' => array(
      'placeholder' => '100',
    ),
  );

  // Number of Dependents.
  $form['number_of_dependents'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Dependents'),
    '#attributes' => array(
      'placeholder' => '200',
    ),
  );

  // Nature of Business/SIC.
  $form['nature_of_business'] = array(
    '#type' => 'textfield',
    '#title' => t('Nature of Business/SIC'),
    '#attributes' => array(
      'placeholder' => 'xxxx',
    ),
  );

  // Years in Business.
  $form['years_in_business'] = array(
    '#type' => 'textfield',
    '#title' => t('Years in Business'),
    '#attributes' => array(
      'placeholder' => '5',
    ),
  );

  // Tax ID.
  $form['tax_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Tax ID'),
    '#attributes' => array(
      'placeholder' => 'xxxxxxxxx',
    ),
  );

  // Renewal Date.
  $form['renewal_date'] = array(
    '#type' => 'date_popup',
    '#date_format' => 'm/d/Y',
    '#default_value' => 'YYYY-MM-DD',
    '#date_year_range' => '0:+3',
    '#title' => t('Renewal Date'),
  );

  // Attachments.
  $form['attachments_container'] = array(
    '#type' => 'container',
    'attachment' => array(),
  );

  $form['attachments_container']['attachment']['employee_census'] = array(
    '#title' => t('Employee Census'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['current_summary_of_benefit'] = array(
    '#title' => t('Current Summary of Benefit'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['current_bill'] = array(
    '#title' => t('Current Bill'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['last_renewal_letter'] = array(
    '#title' => t('Last Renewal Letter & Rates'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['summary_of_monthly_claims_experience'] = array(
    '#title' => t('Summary of Monthly Claims Experience'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['broker_of_record'] = array(
    '#title' => t('Broker of Record'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['letter_of_authorization'] = array(
    '#title' => t('Letter of Authorization'),
    '#type' => 'managed_file',
  );

  $form['attachments_container']['attachment']['large_claims_report'] = array(
    '#title' => t('Large Claims Report'),
    '#type' => 'managed_file',
  );

  // Census checkboxes.
  $form['census_container'] = array(
    '#type' => 'container',
    'census' => array(),
  );

  $form['census_container']['census']['check_identifier'] = array(
    '#type' => 'checkbox',
    '#title' => t('Identifier (Name or Employee Number)'),
  );

  $form['census_container']['census']['check_ssn'] = array(
    '#type' => 'checkbox',
    '#title' => t('Social Security Number'),
  );

  $form['census_container']['census']['check_date_birth_age'] = array(
    '#type' => 'checkbox',
    '#title' => t('Date of Birth or Age'),
  );

  $form['census_container']['census']['check_gender'] = array(
    '#type' => 'checkbox',
    '#title' => t('Gender'),
  );

  $form['census_container']['census']['check_home_zip_codes'] = array(
    '#type' => 'checkbox',
    '#title' => t('Home Zip Codes for each employee'),
  );

  $form['census_container']['census']['check_plan_selection'] = array(
    '#type' => 'checkbox',
    '#title' => t('Plan Selection (HMO, PPO, HSA, etc.)'),
  );

  $form['census_container']['census']['check_tier_levels'] = array(
    '#type' => 'checkbox',
    '#title' => t('Tier Levels (EE, ES, EC(H), EF) or 3 Tiers (if applicable)'),
  );

  $form['census_container']['census']['check_identification_of_retirees'] = array(
    '#type' => 'checkbox',
    '#title' => t('Identification of Retirees or COBRA members with COBRA Termination Date'),
  );

  $form['census_container']['census']['check_identification_of_covered'] = array(
    '#type' => 'checkbox',
    '#title' => t('Identification of covered and not covered employees with explanation for those not (i.e. spousal, medicare, medicaid, etc.)'),
  );

  $form['carrier_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Carier Name'),
  );

  $form['primary_contact_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Primary Contact'),
  );

  $form['primary_contact_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email Address'),
  );

  $form['major_medical'] = array(
    '#type' => 'checkbox',
    '#title' => t('Major Medical'),
    '#default_value' => $_GET['benefits']['major_medical'],
  );

  $form['limited_medical'] = array(
    '#type' => 'checkbox',
    '#title' => t('Limited Medical'),
    '#default_value' => $_GET['benefits']['limited_medical'],
  );

  $form['teledoc'] = array(
    '#type' => 'checkbox',
    '#title' => t('Teledoc'),
    '#default_value' => $_GET['benefits']['teledoc'],
  );

  $form['mec'] = array(
    '#type' => 'checkbox',
    '#title' => t('MEC'),
    '#default_value' => $_GET['benefits']['mec'],
  );

  $form['dental'] = array(
    '#type' => 'checkbox',
    '#title' => t('Dental'),
    '#default_value' => $_GET['benefits']['dental'],
  );

  $form['vision'] = array(
    '#type' => 'checkbox',
    '#title' => t('Vision'),
    '#default_value' => $_GET['benefits']['vision'],
  );

  $form['life'] = array(
    '#type' => 'checkbox',
    '#title' => t('Life & AD&D'),
    '#default_value' => $_GET['benefits']['life'],
  );

  $form['short_term_disability'] = array(
    '#type' => 'checkbox',
    '#title' => t('Short Term Dissability'),
    '#default_value' => $_GET['benefits']['short_term_disability'],
  );

  $form['special_benefits'] = array(
    '#type' => 'checkbox',
    '#title' => t('Special Benefits'),
    '#default_value' => $_GET['benefits']['special_benefits'],
  );

  $form['retirement'] = array(
    '#type' => 'checkbox',
    '#title' => t('Retirement'),
    '#default_value' => $_GET['benefits']['retirement'],
  );

  // Major Medical.
  $form['major_medical_fields'] = array(
    '#type' => 'container',
    'mm_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'mm_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'mm_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'mm_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'mm_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'mm_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'mm_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'mm_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
  );

  // Limited Medical.
  $form['limited_medical_fields'] = array(
    '#type' => 'container',
    'lm_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'lm_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'lm_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'lm_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'lm_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'lm_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'lm_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'lm_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
  );

  // Telemedicine.
  $form['telemedicine_fields'] = array(
    '#type' => 'container',
    'tel_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'tel_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'tel_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'tel_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'tel_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'tel_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'tel_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'tel_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
  );

  // MEC.
  $form['mec_fields'] = array(
    '#type' => 'container',
    'mec_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'mec_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'mec_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'mec_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'mec_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'mec_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'mec_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'mec_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
  );

  // Dental.
  $form['dental_fields'] = array(
    '#type' => 'container',
    'den_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'den_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'den_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'den_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'den_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'den_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'den_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'den_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
  );

  // Vision.
  $form['vision_fields'] = array(
    '#type' => 'container',
    'vs_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'vs_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'vs_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'vs_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'vs_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'vs_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'vs_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'vs_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
  );

  // Life.
  $form['life_fields'] = array(
    '#type' => 'container',
    'lf_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'lf_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'lf_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'lf_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'lf_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'lf_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'lf_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'lf_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
  );

  // Short Term Disability.
  $form['short_term_disability_fields'] = array(
    '#type' => 'container',
    'std_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'std_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'std_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'std_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'std_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'std_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'std_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'std_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
  );

  // Retirement.
  $form['retirement_fields'] = array(
    '#type' => 'container',
    'ret_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'ret_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'ret_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'ret_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'ret_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'ret_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'ret_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'ret_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
  );

  // Special Benefits.
  $form['special_benefits_fields'] = array(
    '#type' => 'container',
    'sb_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Carrier Name'),
      ),
    ),
    'sb_years_with_current_carrier' => array(
      '#type' => 'textfield',
      '#title' => t('Years with Current Carrier'),
      '#attributes' => array(
        'placeholder' => t('Type Number of Years'),
      ),
    ),
    'sb_plan_year_to_quote_start' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'sb_plan_year_to_quote_end' => array(
      '#type' => 'date_popup',
      '#date_format' => 'm/d/Y',
      '#default_value' => 'YYYY-MM-DD 00:00:00',
      '#date_year_range' => '0:+3',
    ),
    'sb_renewal_of_current_plan' => array(
      '#type' => 'radios',
      '#title' => t('Is this a renewal of a current plan in BullsEye?'),
      '#options' => array(
        1 => 'Yes',
        0 => 'No',
      ),
      '#default_value' => 1,
    ),
    'sb_percentage_single' => array(
      '#type' => 'textfield',
      '#title' => t('Single'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'sb_percentage_family' => array(
      '#type' => 'textfield',
      '#title' => t('Family'),
      '#attributes' => array(
        'placeholder' => t('50%'),
      ),
    ),
    'sb_waiting_period' => array(
      '#type' => 'textfield',
      '#title' => t('Wating Period for New Employees?'),
      '#attributes' => array(
        'placeholder' => t('15 Days'),
      ),
    ),
  );

  // The values for the dropdown box.
  $form['type_options'] = array(
    '#type' => 'value',
    '#value' => array(
      'high' => t('High'),
      'normal' => t('Normal'),
      'low' => t('Low'),
    ),
  );

  $form['priority'] = array(
    '#title' => t('Priority'),
    '#type' => 'select',
    '#description' => "Select the priority level.",
    '#options' => $form['type_options']['#value'],
  );

  $form['due_date'] = array(
    '#type' => 'date_popup',
    '#date_format' => 'm/d/Y',
    '#default_value' => 'YYYY-MM-DD 00:00:00',
    '#date_year_range' => '0:+3',
    '#size' => 12,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save and Exit'),
  );

  return $form;
}

/**
 * Form submit for carrier form.
 */
function bullseye_rfp_form_submit($form, &$form_state) {

  global $user;

  $data = $_SESSION['add_rfp'];
  $account = node_load($data['account_id']);

  kpr($form_state['values']);
  die();

  $be = new Bullseye($user);

  // Set the producer name.
  $carrier_name = $form_state['values']['carrier_name'];
  $contact_name = $form_state['values']['primary_contact_name'];
  $contact_email = $form_state['values']['primary_contact_email'];
  $major_medical = $form_state['values']['major_medical'];
  $limited_medical = $form_state['values']['limited_medical'];
  $teledoc = $form_state['values']['teledoc'];
  $mec = $form_state['values']['mec'];
  $dental = $form_state['values']['dental'];
  $vision = $form_state['values']['vision'];
  $life = $form_state['values']['life'];
  $short_term_disability = $form_state['values']['short_term_disability'];
  $special_benefits = $form_state['values']['special_benefits'];
  $retirement = $form_state['values']['retirement'];
  $priority = $form_state['values']['priority'];
  $due_date = $form_state['values']['due_date'];

  // Plan specifications.
  $fringe_rate = $form_state['values']['fringe_rates'];
  $proposed_effective_date = $form_state['values']['proposed_effective_date'];
  $other_work_locations = $form_state['values']['other_work_locations'];
  $number_of_employees = $form_state['values']['number_of_employees'];
  $number_of_dependents = $form_state['values']['number_of_dependents'];
  $nature_of_business = $form_state['values']['nature_of_business'];
  $years_in_business = $form_state['values']['years_in_business'];
  $tax_id = $form_state['values']['tax_id'];
  $renewal_date = $form_state['values']['renewal_date'];

  // Attachments.
  $employee_census = $form_state['values']['employee_census'];
  $current_summary_of_benefit = $form_state['values']['current_summary_of_benefit'];
  $current_bill = $form_state['values']['current_bill'];
  $last_renewal_letter = $form_state['values']['last_renewal_letter'];
  $summary_of_monthly_claims_experience = $form_state['values']['summary_of_monthly_claims_experience'];
  $broker_of_record = $form_state['values']['broker_of_record'];
  $letter_of_authorization = $form_state['values']['letter_of_authorization'];
  $large_claims_report = $form_state['values']['large_claims_report'];

  // Census inclusions.
  $check_identifier = $form_state['values']['check_identifier'];
  $check_ssn = $form_state['values']['check_ssn'];
  $check_date_birth_age = $form_state['values']['check_date_birth_age'];
  $check_gender = $form_state['values']['check_gender'];
  $check_home_zip_codes = $form_state['values']['check_home_zip_codes'];
  $check_plan_selection = $form_state['values']['check_plan_selection'];
  $check_tier_levels = $form_state['values']['check_tier_levels'];
  $check_identification_of_retirees = $form_state['values']['check_identification_of_retirees'];
  $check_identification_of_covered = $form_state['values']['check_identification_of_covered'];

  // Benefits.
  // Major medical benefits.
  $mm_current_carrier = $form_state['values']['mm_current_carrier'];
  $mm_years_with_current_carrier = $form_state['values']['mm_years_with_current_carrier'];
  $mm_plan_year_to_quote_start = $form_state['values']['mm_plan_year_to_quote_start'];
  $mm_plan_year_to_quote_end = $form_state['values']['mm_plan_year_to_quote_end'];
  $mm_renewal_of_current_plan = $form_state['values']['mm_percentage_single'];
  $mm_percentage_family = $form_state['values']['mm_percentage_family'];
  $mm_waiting_period = $form_state['values']['mm_waiting_period'];
  // Limited Medical.
  $lm_current_carrier = $form_state['values']['lm_current_carrier'];
  $lm_years_with_current_carrier = $form_state['values']['lm_years_with_current_carrier'];
  $lm_plan_year_to_quote_start = $form_state['values']['lm_plan_year_to_quote_start'];
  $lm_plan_year_to_quote_end = $form_state['values']['lm_plan_year_to_quote_end'];
  $lm_renewal_of_current_plan = $form_state['values']['lm_renewal_of_current_plan'];
  $lm_percentage_single = $form_state['values']['lm_percentage_single'];
  $lm_percentage_family = $form_state['values']['lm_percentage_family'];
  $lm_waiting_period = $form_state['values']['lm_waiting_period'];
  // Teledoc.
  $tel_current_carrier = $form_state['values']['tel_current_carrier'];
  $tel_years_with_current_carrier = $form_state['values']['tel_years_with_current_carrier'];
  $tel_plan_year_to_quote_start = $form_state['values']['tel_plan_year_to_quote_start'];
  $tel_plan_year_to_quote_end = $form_state['values']['tel_plan_year_to_quote_end'];
  $tel_renewal_of_current_plan = $form_state['values']['tel_renewal_of_current_plan'];
  $tel_percentage_single = $form_state['values']['tel_percentage_single'];
  $tel_percentage_family = $form_state['values']['tel_percentage_family'];
  $tel_waiting_period = $form_state['values']['tel_waiting_period'];
  // MEC.
  $mec_current_carrier = $form_state['values']['mec_current_carrier'];
  $mec_years_with_current_carrier = $form_state['values']['mec_years_with_current_carrier'];
  $mec_plan_year_to_quote_start = $form_state['values']['mec_plan_year_to_quote_start'];
  $mec_plan_year_to_quote_end = $form_state['values']['mec_plan_year_to_quote_end'];
  $mec_renewal_of_current_plan = $form_state['values']['mec_renewal_of_current_plan'];
  $mec_percentage_single = $form_state['values']['mec_percentage_single'];
  $mec_percentage_family = $form_state['values']['mec_percentage_family'];
  $mec_waiting_period = $form_state['values']['mec_waiting_period'];

  $node = new stdClass();

  $node->title = $carrier_name;

  $node->type = "rfp";
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;
  $node->uid = $user->uid;
  $node->status = 1;
  $node->promote = 0;
  $node->comment = 0;

  // For contact name.
  if ($contact_name) {
    $node->field_primary_contact[$node->language][0]['value'] = $contact_name;
  }

  // For contact email.
  if ($contact_email) {
    $node->field_email[$node->language][0]['value'] = $contact_email;
  }

  // For major medical.
  if ($major_medical == 1) {
    $node->field_benefits[$node->language][]['value'] = 'major_medical';
  }
  if ($limited_medical == 1) {
    $node->field_benefits[$node->language][]['value'] = 'limited_medical';
  }
  if ($teledoc == 1) {
    $node->field_benefits[$node->language][]['value'] = 'teledoc';
  }
  if ($mec == 1) {
    $node->field_benefits[$node->language][]['value'] = 'mec';
  }
  if ($dental == 1) {
    $node->field_benefits[$node->language][]['value'] = 'dental';
  }
  if ($vision == 1) {
    $node->field_benefits[$node->language][]['value'] = 'vision';
  }
  if ($life == 1) {
    $node->field_benefits[$node->language][]['value'] = 'life';
  }
  if ($short_term_disability == 1) {
    $node->field_benefits[$node->language][]['value'] = 'short_term_disability';
  }
  if ($special_benefits == 1) {
    $node->field_benefits[$node->language][]['value'] = 'special_benefits';
  }
  if ($retirement == 1) {
    $node->field_benefits[$node->language][]['value'] = 'retirement';
  }

  if ($priority) {
    $node->field_priority[$node->language][0]['value'] = $priority;
  }

  if ($due_date) {
    $node->field_due_date[$node->language][0]['value'] = $due_date;
  }

  if ($priority) {
    $node->field_priority[$node->language][0]['value'] = $priority;
  }

  // Save the carrier in the storage.
  $node = node_submit($node);
  node_save($node);

  drupal_set_message(t('Successfully added RFP.'));

  // Invalidate the existing cache to make sure that
  // the newly added one will get indexed too.
  cache_clear_all('rfp_listing', 'cache');
  // Reroute the page to the listing page.
  drupal_goto('/rfps');
}
