<?php

/**
 * @file
 * Author: Ruthie Hallarsis
 * Description: Module for custom BullsEye blocks.
 */

/**
 * Implements hook_menu().
 */
function bullseye_blocks_menu() {
  $items = array();

  $items['accounts'] = array(
    'title' => 'Accounts',
    'page callback' => '_empty_page',
    'access arguments' => array('access accounts page'),
    'type' => MENU_CALLBACK
  );

  $items['accounts/leads'] = array(
    'title' => 'Leads',
    'page callback' => '_empty_page',
    'access arguments' => array('access accounts leads page'),
    'type' => MENU_CALLBACK
  );

  $items['accounts/prospects'] = array(
    'title' => 'Prospects',
    'page callback' => '_empty_page',
    'access arguments' => array('access accounts prospects page'),
    'type' => MENU_CALLBACK
  );

  $items['accounts/opportunities'] = array(
    'title' => 'Opportunities',
    'page callback' => '_empty_page',
    'access arguments' => array('access accounts opportunities page'),
    'type' => MENU_CALLBACK
  );

  $items['accounts/deals-in-progress'] = array(
    'title' => 'Deals in Progress',
    'page callback' => '_empty_page',
    'access arguments' => array('access accounts deals progress page'),
    'type' => MENU_CALLBACK
  );

  $items['accounts/closed-deals'] = array(
    'title' => 'Closed Deals',
    'page callback' => '_empty_page',
    'access arguments' => array('access accounts closed deals page'),
    'type' => MENU_CALLBACK
  );

  $items['calendar'] = array(
    'title' => 'Activities',
    'page callback' => '_empty_page',
    'access arguments' => array('access calendar page'),
    'type' => MENU_CALLBACK
  );

  $items['rfps'] = array(
    'title' => 'RFPs',
    'page callback' => '_empty_page',
    'access arguments' => array('access rfps page'),
    'type' => MENU_CALLBACK
  );

  $items['proposals'] = array(
    'title' => 'Proposals',
    'page callback' => '_empty_page',
    'access arguments' => array('access proposals page'),
    'type' => MENU_CALLBACK
  );

  $items['producers'] = array(
    'title' => 'Producers',
    'page callback' => '_empty_page',
    'access arguments' => array('access producers page'),
    'type' => MENU_CALLBACK
  );

  $items['producers/pending'] = array(
    'title' => 'Pending Producer Requests',
    'page callback' => '_empty_page',
    'access arguments' => array('access producers pending page'),
    'type' => MENU_CALLBACK
  );

  $items['carriers'] = array(
    'title' => 'Carriers',
    'page callback' => '_empty_page',
    'access arguments' => array('access carriers page'),
    'type' => MENU_CALLBACK
  );

  $items['files'] = array(
    'title' => 'Files',
    'page callback' => '_empty_page',
    'access arguments' => array('access files page'),
    'type' => MENU_CALLBACK
  );

  $items['company'] = array(
    'title' => 'Company',
    'page callback' => '_empty_page',
    'access arguments' => array('access files page'),
    'type' => MENU_CALLBACK
  );

  $items['suggestion-box'] = array(
    'title' => 'Company',
    'page callback' => 'suggestion_box_send',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  $items['mailchimp'] = array(
    'title' => 'Mailchimp',
    'page callback' => '_empty_page',
    'access arguments' => array('access mailchimp page'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function bullseye_blocks_permission() {
  return array(
    'access accounts page' => array(
      'title' => t('Accounts Page'),
      'description' => t('Access the accounts page.'),
    ),
    'access accounts leads page' => array(
      'title' => t('Accounts/Leads Page'),
      'description' => t('Access the accounts/leads page.'),
    ),
    'access accounts prospects page' => array(
      'title' => t('Accounts/Prospects Page'),
      'description' => t('Access the accounts/prospects page.'),
    ),
    'access accounts opportunities page' => array(
      'title' => t('Accounts/Opportunities Page'),
      'description' => t('Access the accounts/opportunities page.'),
    ),
    'access accounts deals progress page' => array(
      'title' => t('Accounts/Deals in Progress Page'),
      'description' => t('Access the accounts/deals-in-progress page.'),
    ),
    'access accounts closed deals page' => array(
      'title' => t('Accounts/Closed Deals Page'),
      'description' => t('Access the accounts/closed-deals page.'),
    ),
    'access calendar page' => array(
      'title' => t('Calendar Page'),
      'description' => t('Access the calendar page.'),
    ),
    'access rfps page' => array(
      'title' => t('RFPs Page'),
      'description' => t('Access the rfps page.'),
    ),
    'access producers page' => array(
      'title' => t('Producers Page'),
      'description' => t('Access the producers page.'),
    ),
    'access producers pending page' => array(
      'title' => t('Producers Page'),
      'description' => t('Access the producers pending page.'),
    ),
    'access proposals page' => array(
      'title' => t('Proposals Page'),
      'description' => t('Access the proposals page.'),
    ),
    'access carriers page' => array(
      'title' => t('Carriers Page'),
      'description' => t('Access the carriers page.'),
    ),
    'access files page' => array(
      'title' => t('Files Page'),
      'description' => t('Access the files page.'),
    ),
    'access mailchimp page' => array(
      'title' => t('Mailchimp Page'),
      'description' => t('Access the Mailchimp page.'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function bullseye_blocks_form_alter(&$form, &$form_state, $form_id) {
  
  // Custom forms.
  $custom_close_lightbox_forms = array(
    'bullseye_leads_import_leads',
    'bullseye_producer_form',
    'bullseye_carriers_form',
    'bullseye_proposals_email_form',
    'bullseye_account_new_form',
    'producer_assign_form',
    'accounts_delete_form',
    'rfps_delete_form',
    'proposals_delete_form',
    'producers_delete_form',
    'carriers_delete_form',
    'bullseye_event_edit_task',
    'bullseye_event_close_tasks',
    'mailchimp_admin_settings',
  );

  // Default drupal forms.
  $default_close_lightbox_forms = array(
    'accounts_node_form',
  );

  if (in_array($form_id, $custom_close_lightbox_forms)) {
    $form['#submit'][] = '_close_lightbox';
  }

  if (in_array($form_id, $default_close_lightbox_forms)) {
    $form['actions']['submit']['#submit'][] = '_close_lightbox';
  }
}

/**
 * Closing the lightbox.
 */
function _close_lightbox($form, &$form_state) {
  print '<script>parent.location.reload();</script>';
  print '<script>parent.Lightbox.end();</script>';
  die();
}

/**
 * Implements hook_theme().
 */
function bullseye_blocks_theme() {
  // Init vars.
  $template_path = drupal_get_path('module', 'bullseye_blocks') . '/templates';

  // Return theme definitions.
  return array(

    // Top Header Block.
    'be_top_header' => array(
      'variables' => array(),
      'template' => 'be-top-header',
      'path' => $template_path,
    ),

    // Bottom Header Block.
    'be_bottom_header' => array(
      'variables' => array(),
      'template' => 'be-bottom-header',
      'path' => $template_path,
    ),

    // Leads Table Block.
    'be_leads' => array(
      'variables' => array(),
      'template' => 'be-leads',
      'path' => $template_path,
    ),

    // Accounts Table Block.
    'be_accounts' => array(
      'variables' => array(),
      'template' => 'be-accounts',
      'path' => $template_path,
    ),

    // Prospects Table Block.
    'be_prospects' => array(
      'variables' => array(),
      'template' => 'be-prospects',
      'path' => $template_path,
    ),

    // Opportunities Table Block.
    'be_opportunities' => array(
      'variables' => array(),
      'template' => 'be-opportunities',
      'path' => $template_path,
    ),

    // Deals-in-Progress Table Block.
    'be_deals_in_progress' => array(
      'variables' => array(),
      'template' => 'be-deals-in-progress',
      'path' => $template_path,
    ),

    // Closed Deals Table Block.
    'be_closed_deals' => array(
      'variables' => array(),
      'template' => 'be-closed-deals',
      'path' => $template_path,
    ),

    // Proposals Table Block.
    'be_proposals' => array(
      'variables' => array(),
      'template' => 'be-proposals',
      'path' => $template_path,
    ),

    // Producers Table Block.
    'be_producers' => array(
      'variables' => array(),
      'template' => 'be-producers',
      'path' => $template_path,
    ),

    // Producers Pending Table Block.
    'be_producers_pending' => array(
      'variables' => array(),
      'template' => 'be-producers-pending',
      'path' => $template_path,
    ),

    // Carriers Table Block.
    'be_carriers' => array(
      'variables' => array(),
      'template' => 'be-carriers',
      'path' => $template_path,
    ),

    // Current Progress Block.
    'be_current_progress' => array(
      'variables' => array(),
      'template' => 'be-current-progress',
      'path' => $template_path,
    ),

    // Create Event Block.
    'be_create_event' => array(
      'variables' => array(),
      'template' => 'be-create-event',
      'path' => $template_path,
    ),

    // Recent Activities Block.
    'be_recent_activities' => array(
      'variables' => array(),
      'template' => 'be-recent-activities',
      'path' => $template_path,
    ),

    // Account Details Block.
    'be_account_details' => array(
      'variables' => array(),
      'template' => 'be-account-details',
      'path' => $template_path,
    ),

    // People Block.
    'be_people' => array(
      'variables' => array(),
      'template' => 'be-people',
      'path' => $template_path,
    ),

    // Files Block.
    'be_files' => array(
      'variables' => array(),
      'template' => 'be-files',
      'path' => $template_path,
    ),

    // Header Progress Block.
    'be_header_progress' => array(
      'variables' => array(),
      'template' => 'be-header-progress',
      'path' => $template_path,
    ),

    // RFPs Table Block.
    'be_rfps' => array(
      'variables' => array(),
      'template' => 'be-rfps',
      'path' => $template_path,
    ),

    // Calendar Block.
    'be_calendar_activities' => array(
      'variables' => array(),
      'template' => 'be-calendar-activities',
      'path' => $template_path,
    ),

    // Activities Block.
    'be_activities' => array(
      'variables' => array(),
      'template' => 'be-activities',
      'path' => $template_path,
    ),

    // Tasks Block.
    'be_tasks' => array(
      'variables' => array(),
      'template' => 'be-tasks',
      'path' => $template_path,
    ),

    // Dashboard Statistics Block.
    'be_dashboard_statistics' => array(
      'variables' => array(),
      'template' => 'be-dashboard-statistics',
      'path' => $template_path,
    ),

    // Dashboard Revenue Block.
    'be_dashboard_revenue' => array(
      'variables' => array(),
      'template' => 'be-dashboard-revenue',
      'path' => $template_path,
    ),

    // Dashboard Performance Block.
    'be_dashboard_performance' => array(
      'variables' => array(),
      'template' => 'be-dashboard-performance',
      'path' => $template_path,
    ),

    // Mailchimp Table Block.
    'be_mailchimp' => array(
      'variables' => array(),
      'template' => 'be-mailchimp',
      'path' => $template_path,
    ),

    // Mailchimp Table Block.
    'be_mailbox' => array(
      'variables' => array(),
      'template' => 'be-mailbox',
      'path' => $template_path,
    ),

    // Mailchimp Table Block.
    'be_starred_contacts' => array(
      'variables' => array(),
      'template' => 'be-starred-contacts',
      'path' => $template_path,
    ),

  );
}

/**
 * Implements hook_block_info().
 */
function bullseye_blocks_block_info() {
  // Init vars.
  $blocks = array();

  // Top Header Block.
  $blocks['be_top_header'] = array(
    'info' => t('Top Header'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Bottom Header Block.
  $blocks['be_bottom_header'] = array(
    'info' => t('Bottom Header'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Leads Table Block.
  $blocks['be_leads'] = array(
    'info' => t('Leads Block (Table)'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Accounts Table Block.
  $blocks['be_accounts'] = array(
    'info' => t('Accounts Block (Table)'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Prospects Table Block.
  $blocks['be_prospects'] = array(
    'info' => t('Prospects Block (Table)'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Opportunities Table Block.
  $blocks['be_opportunities'] = array(
    'info' => t('Opportunities Block (Table)'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Deals-in-Progress Table Block.
  $blocks['be_deals_in_progress'] = array(
    'info' => t('Deals-in-Progress Block (Table)'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Closed Deals Table Block.
  $blocks['be_closed_deals'] = array(
    'info' => t('Closed Deals Block (Table)'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Proposals Table Block.
  $blocks['be_proposals'] = array(
    'info' => t('Proposals Block (Table)'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Producers Table Block.
  $blocks['be_producers'] = array(
    'info' => t('Producers Block (Table)'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Producers Pending Table Block.
  $blocks['be_producers_pending'] = array(
    'info' => t('Producers Pending Block (Table)'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Carriers Table Block.
  $blocks['be_carriers'] = array(
    'info' => t('Carriers Block (Table)'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Current Progress Block.
  $blocks['be_current_progress'] = array(
    'info' => t('Current Progress Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Create Event Block.
  $blocks['be_create_event'] = array(
    'info' => t('Create Event Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Recent Activities Block.
  $blocks['be_recent_activities'] = array(
    'info' => t('Recent Activities Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Account Details Block.
  $blocks['be_account_details'] = array(
    'info' => t('Account Details Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // People Block.
  $blocks['be_people'] = array(
    'info' => t('People Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Files Block.
  $blocks['be_files'] = array(
    'info' => t('Files Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Header Progress Block.
  $blocks['be_header_progress'] = array(
    'info' => t('Header Progress Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // RFPs Table Block.
  $blocks['be_rfps'] = array(
    'info' => t('RFPs Block (Table)'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Calendar Block.
  $blocks['be_calendar_activities'] = array(
    'info' => t('Calendar Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Activities Block.
  $blocks['be_activities'] = array(
    'info' => t('Activities Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Tasks Block.
  $blocks['be_tasks'] = array(
    'info' => t('Tasks Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Dashboard Statistics Block.
  $blocks['be_dashboard_statistics'] = array(
    'info' => t('Dashboard - Statistics Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Dashboard Revenue Block.
  $blocks['be_dashboard_revenue'] = array(
    'info' => t('Dashboard - Revenue Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Dashboard Performance Block.
  $blocks['be_dashboard_performance'] = array(
    'info' => t('Dashboard - Performance Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Mailchimp Table Block.
  $blocks['be_mailchimp'] = array(
    'info' => t('Mailchimp Block (Table)'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Mailbox Block.
  $blocks['be_mailbox'] = array(
    'info' => t('Dashboard - Mailbox Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  // Starred Contacts Block.
  $blocks['be_starred_contacts'] = array(
    'info' => t('Dashboard - Starred Contacts Block'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );
  
  // Return block definitions.
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function bullseye_blocks_block_view($delta = '') {

  // Init vars.
  $block = array();

  // Get block helpers file.
  module_load_include('inc', 'bullseye_blocks', 'bullseye_blocks.blocks');

  // Based on the delta, get the approdiate render block.
  $function = 'bullseye_blocks_render_' . $delta;

  // Get block content.
  $block = $function();
  
  return $block;
}

/**
 * Implements hook_preprocess_block().
 */
function bullseye_blocks_preprocess_block(&$variables) {

  // Define block column classes for bullseye_blocks.
  if ($variables['block']->module == 'bullseye_blocks') {
    if ($variables['block']->delta == 'be_leads' || 
        $variables['block']->delta == 'be_accounts' ||
        $variables['block']->delta == 'be_prospects' ||
        $variables['block']->delta == 'be_opportunities' ||
        $variables['block']->delta == 'be_deals_in_progress' ||
        $variables['block']->delta == 'be_closed_deals' ||
        $variables['block']->delta == 'be_proposals' ||
        $variables['block']->delta == 'be_producers' ||
        $variables['block']->delta == 'be_carriers' ||
        $variables['block']->delta == 'be_dashboard_statistics' ||
        $variables['block']->delta == 'be_mailchimp') {
      $variables['classes_array'][] = 'col-md-12';
    }
    if ($variables['block']->delta == 'be_dashboard_revenue' || 
        $variables['block']->delta == 'be_dashboard_performance' ||
        $variables['block']->delta == 'be_mailbox' ||
        $variables['block']->delta == 'be_starred_contacts') {
      $variables['classes_array'][] = 'col-md-6';
    }
  }

  if ($variables['block']->module == 'system') {
    if ($variables['block']->delta == 'main') {
      if (arg(0) == 'gmail-connector') {
        $variables['classes_array'][] = 'col-md-12';
      }
    }
  }
}

/**
 * Empty Callback for empty page.
 */
function _empty_page() {
  $empty = ' ';
  return $empty;
}

/**
 * Callback for suggestion box sending.
 */
function suggestion_box_send() {
  global $user;

  $name = $_POST['name'];
  $content_subject = $_POST['content_subject'];
  $details = $_POST['details'];

  $to = 'support@archerjordan.com';
  $from = $user->mail;
  $subject = 'BULLSEYE USER FEEDBACK - ' . date('F d, Y');
  $message = "\r\nName: " . $name . "\r\nEmail: " . $from . "\r\nDate: " . date('F d, Y') . "\r\n\r\nSubject: " . $content_subject . "\r\n\r\nComment/Suggestion:\r\n" . $details;
  $attachments = array();

  $data = array();

  // Send the email.
  // Send the proposal via email.
  $params = array(
    'key' => 'bullseye',
    'to' => $to,
    'from' => $from,
    'subject' => $subject,
    'body' => $message,
    'attachment' => $attachments,
  );
  Bullseye::sendEmail($to, $from, $params);

  drupal_json_output('success');

}