<?php
/**
 * Bullseye event module.
 */

/**
 * Implements hook_menu().
 */
function bullseye_event_menu() {
  $items = array();

  $items['be-event/save-activity'] = array(
    'page callback' => 'bullseye_event_save_activity',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['be-event/save-task'] = array(
    'page callback' => 'bullseye_event_save_task',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['be-event/load-activities'] = array(
    'page callback' => 'bullseye_event_load_activities',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  $items['be-event/calendar-load-tasks'] = array(
    'page callback' => 'bullseye_event_calendar_load_tasks',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['be-event/selected-tasks'] = array(
    'page callback' => 'bullseye_event_selected_tasks',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  $items['be-event/get-selected-tasks'] = array(
    'page callback' => 'bullseye_event_get_selected_tasks',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['be-event/calendar-load-activities'] = array(
    'page callback' => 'bullseye_event_calendar_load_activities',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['be-event/edit-task'] = array(
    'title' => 'Send Proposal',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bullseye_event_edit_task'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['be-event/close-tasks'] = array(
    'title' => 'Close Tasks',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bullseye_event_close_tasks'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function bullseye_event_theme() {
  // Init vars.
  $template_path = drupal_get_path('module', 'bullseye_event') . '/templates';

  // Return theme definitions.
  return array(

    'be_recent_activities_rows' => array(
      'variables' => array(),
      'template' => 'be-recent-activities-rows',
      'path' => $template_path,
    ),

    'be_calendar_tab_tasks_rows' => array(
      'variables' => array(),
      'template' => 'be-calendar-tab-tasks-rows',
      'path' => $template_path,
    ),

    'be_calendar_tab_activities_rows' => array(
      'variables' => array(),
      'template' => 'be-calendar-tab-activities-rows',
      'path' => $template_path,
    ),

  );
}

/**
 * Save the activity.
 */
function bullseye_event_save_activity() {

	global $user;

	$nid = $_POST['nid'];
	$activity_name = $_POST['activity_name'];
  $type = $_POST['type'];
  $contact = $_POST['contact'];
  $date = strtotime($_POST['date']);
  $priority = $_POST['priority'];
  $contact_details = Bullseye::getContactDetailsById($contact);
  $firstname = $contact_details['field_firstname_value'];
  $lastname = $contact_details['field_lastname_value'];
  $contact_name = $firstname . ' ' . $lastname;

  $node = new stdClass();
  $node->type = 'task';
  $node->uid = $user->uid;
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;

  if ($type == 'phone_call') {
  	$title = 'Phone call with ' . $contact_name;
    cache_clear_all('recent_events_phonecall_' . $nid, 'cache');
  }
  elseif ($type == 'email') {
  	$title = 'Email to ' . $contact_name;
    cache_clear_all('recent_events_email_' . $nid, 'cache');
  }
  elseif ($type == 'meeting') {
  	$title = 'Meeting with ' . $contact_name;
    cache_clear_all('recent_events_meeting_' . $nid, 'cache');
  }
  elseif ($type == 'others') {
  	$title = $activity_name . ' with ' . $contact_name;
    cache_clear_all('recent_events_others_' . $nid, 'cache');
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper->title->set($title);
  $wrapper->field_event_name->set($activity_name);
  $wrapper->field_task_type->set($type);
  $wrapper->field_due_date->set($date);
  $wrapper->field_contact->set($contact);
  $wrapper->field_priority->set($priority);
  $wrapper->field_account->set($nid);
  $wrapper->field_if_system_generated->set('no');
  $wrapper->field_task_status->set('closed');
  $wrapper->field_assigned_to->set('');
  $wrapper->field_event_type->set('activity');
  
  $wrapper->save();

  cache_clear_all('recent_events_' . $nid, 'cache');

  drupal_json_output($wrapper);
}

/**
 * Save the task.
 */
function bullseye_event_save_task() {

  global $user;

  $be = new Bullseye($user);

  $nid = $_POST['nid'];
  $task_name = $_POST['task_name'];
  $type = $_POST['type'];
  $assigned_to = $_POST['assigned_to'];
  $date = strtotime($_POST['date']);
  $priority = $_POST['priority'];

  $firstname = $be->getAccountFirstName($assigned_to);
  $firstname = ucwords($firstname);
  $lastname = $be->getAccountLastName($assigned_to);
  $lastname = ucwords($lastname);
  $contact_name = $firstname . ' ' . $lastname;

  $node = new stdClass();
  $node->type = 'task';
  $node->uid = $user->uid;
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;

  if ($type == 'phone_call') {
    $title = 'Call with ' . $contact_name;
    cache_clear_all('recent_events_phonecall_' . $nid, 'cache');
  }
  elseif ($type == 'email') {
    $title = 'Email by ' . $contact_name;
    cache_clear_all('recent_events_email_' . $nid, 'cache');
  }
  elseif ($type == 'meeting') {
    $title = 'Meeting with ' . $contact_name;
    cache_clear_all('recent_events_meeting_' . $nid, 'cache');
  }
  elseif ($type == 'others') {
    $title = $task_name . ' with ' . $contact_name;
    cache_clear_all('recent_events_others_' . $nid, 'cache');
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper->title->set($title);
  $wrapper->field_event_name->set($task_name);
  $wrapper->field_task_type->set($type);
  $wrapper->field_due_date->set($date);
  $wrapper->field_contact->set('');
  $wrapper->field_priority->set($priority);
  if ($nid != '') {
    $wrapper->field_account->set($nid);
  }
  $wrapper->field_if_system_generated->set('no');
  $wrapper->field_task_status->set('open');
  $wrapper->field_assigned_to->set($assigned_to);
  $wrapper->field_event_type->set('task');
  
  $wrapper->save();

  cache_clear_all('recent_events_' . $nid, 'cache');

  drupal_json_output($wrapper);
}

/**
 * Edit Existing tasks.
 */
function bullseye_event_edit_task($form, &$form_state) {
  $form = array();

  $task_id = $_GET['nid'];
  $company_id = $_GET['company'];

  $users = Bullseye::getAssignedToField();
  $event = Bullseye::getEventDetailsByNid($task_id);
  $assigned_to = $event['field_assigned_to_value'];

  $date_formatted = date('m/d/Y g:i A', strtotime($event['field_due_date_value']));

  $form['#attributes']['class'][] = 'be-forms be-forms-custom';

  $form['form_title'] = array(
    '#prefix' => '<div class="form-title">',
    '#suffix' => '</div>',
    '#markup' => '<h2>' . t('Edit Task') . '</h2>',
  );

  $form['task_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Task Name'),
    '#default_value' => $event['field_event_name_value'],
  );

  $form['task_type'] = array(
    '#title' => t('Type'),
    '#type' => 'select',
    '#options' => array(
      'phone_call' => t('Phone Call'),
      'meeting' => t('Meeting'),
      'email' => t('Email'),
      'others' => t('Others'),
    ),
    '#default_value' => $event['field_task_type_value'],
  );

  $form['priority'] = array(
    '#title' => t('Priority'),
    '#type' => 'select',
    '#options' => array(
      'high' => t('High'),
      'normal' => t('Normal'),
      'low' => t('Low'),
    ),
    '#default_value' => $event['field_priority_value'],
  );

  $form['assigned_to'] = array(
    '#title' => t('Assigned to'),
    '#type' => 'select',
    '#options' => $users,
    '#default_value' => $assigned_to,
  );

  $form['due_date'] = array(
    '#type' => 'textfield',
    '#title' => t('Due Date'),
    '#default_value' => $date_formatted,
  );

  $form['status'] = array(
    '#title' => t('Status'),
    '#type' => 'select',
    '#options' => array(
      'open' => t('Open'),
      'closed' => t('Closed'),
    ),
    '#default_value' => $event['field_task_status_value'],
  );

  $form['submit_container'] = array(
    '#type' => 'container',
  );

  $form['submit_container']['cancel'] = array(
    '#markup' => '<a class="gray-btn" href="/" onClick="parent.Lightbox.end();">Cancel</a>',
  );

  $form['submit_container']['submit'] = array(
    '#type' => 'submit',
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
    '#value' => t('Save'),
  );

  return $form;
}

/**
 * Submit handler for edit task form.
 */
function bullseye_event_edit_task_submit($form, &$form_state) {
  global $user;

  $be = new Bullseye($user);

  $task_id = $_GET['nid'];
  $company_id = $_GET['company'];

  $activity_name = $form_state['values']['task_name'];
  $type = $form_state['values']['task_type'];
  $assigned_to = $form_state['values']['assigned_to'];
  $date = strtotime($form_state['values']['due_date']);
  $priority = $form_state['values']['priority'];
  $firstname = $be->getAccountFirstName($assigned_to);
  $firstname = ucwords($firstname);
  $lastname = $be->getAccountLastName($assigned_to);
  $lastname = ucwords($lastname);
  $contact_name = $firstname . ' ' . $lastname;
  $event_type = 'task';
  $status = $form_state['values']['status'];

  if ($type == 'phone_call') {
    $title = 'Call with ' . $contact_name;
    cache_clear_all('recent_events_phonecall_' . $company_id, 'cache');
  }
  elseif ($type == 'email') {
    $title = 'Email by ' . $contact_name;
    cache_clear_all('recent_events_email_' . $company_id, 'cache');
  }
  elseif ($type == 'meeting') {
    $title = 'Meeting with ' . $contact_name;
    cache_clear_all('recent_events_meeting_' . $company_id, 'cache');
  }
  elseif ($type == 'others') {
    $title = $activity_name . ' with ' . $contact_name;
    cache_clear_all('recent_events_others_' . $company_id, 'cache');
  }

  $wrapper = entity_metadata_wrapper('node', $task_id);
  $wrapper->title->set($title);
  $wrapper->field_event_name->set($activity_name);
  $wrapper->field_task_type->set($type);
  $wrapper->field_due_date->set($date);
  $wrapper->field_contact->set('');
  $wrapper->field_priority->set($priority);
  $wrapper->field_account->set($company_id);
  $wrapper->field_if_system_generated->set('no');
  $wrapper->field_task_status->set($status);
  $wrapper->field_assigned_to->set($assigned_to);
  $wrapper->field_event_type->set('task');
  
  $wrapper->save();

  cache_clear_all('recent_events_' . $company_id, 'cache');
  cache_clear_all('event_details_' . $task_id, 'cache');

  drupal_set_message('Successfully updated task.');
}

/**
 * Close selected tasks.
 */
function bullseye_event_close_tasks() {
  global $user;
  $form = array();

  $be = new Bullseye($user);

  $form['#attributes']['class'][] = 'be-forms be-forms-custom';

  if (isset($_SESSION['calendar_tab_tasks_ids_' . $user->uid]) && !empty($_SESSION['calendar_tab_tasks_ids_' . $user->uid])) {

    $task_ids = $_SESSION['calendar_tab_tasks_ids_' . $user->uid];

    $items_div = '';

    foreach ($task_ids as $key => $value) {
      $event = Bullseye::getEventDetailsByNid($value);
      $title = $event['title'];
      $firstname = $be->getAccountFirstName($event['uid']);
      $firstname = ucwords($firstname);
      $lastname = $be->getAccountLastName($event['uid']);
      $lastname = ucwords($lastname);
      $name = $firstname . ' ' . $lastname;
      $date = date('M j', strtotime($event['field_due_date_value']));
      $markup = $title . ' by ' . $name . ' (Due on ' . $date . ')';
      $items_div .= '<div class="be-item">' . $markup . '</div>';
    }

    $form['form_title'] = array(
      '#prefix' => '<div class="form-title">',
      '#suffix' => '</div>',
      '#markup' => '<h2>' . t('Are you sure you want to close the following tasks?') . '</h2>',
    );

    $form['items'] = array(
      '#prefix' => '<div class="be-items-multiple">',
      '#markup' => $items_div,
      '#suffix' => '</div>',
    );

    $form['submit_container'] = array(
      '#type' => 'container',
    );

    $form['submit_container']['cancel'] = array(
      '#markup' => '<a class="gray-btn" href="/" onClick="parent.Lightbox.end();">Cancel</a>',
    );

    $form['submit_container']['submit'] = array(
      '#type' => 'submit',
      '#attributes' => array(
        'class' => array('green-btn'),
      ),
      '#value' => t('Close Tasks'),
    );
  }
  else {
    $form['form_title'] = array(
      '#prefix' => '<div class="form-title">',
      '#suffix' => '</div>',
      '#markup' => '<h2>' . t('You did not select any items. Please select items first.') . '</h2>',
    );

    $form['submit_container'] = array(
      '#type' => 'container',
    );

    $form['submit_container']['cancel'] = array(
      '#markup' => '<a class="gray-btn" href="/" onClick="parent.Lightbox.end();">Close</a>',
    );
  }

  return $form;
}

/**
 * Form submit for closing selected tasks.
 */
function bullseye_event_close_tasks_submit() {
  global $user;
  $task_ids = $_SESSION['calendar_tab_tasks_ids_' . $user->uid];

  foreach ($task_ids as $key => $value) {
    $wrapper = entity_metadata_wrapper('node', $value);
    $wrapper->field_task_status->set('closed');
    $wrapper->save();
    cache_clear_all('event_details_' . $value, 'cache');
  }

  unset($_SESSION['calendar_tab_tasks_ids_' . $user->uid]);
  drupal_set_message('Successfully closed tasks.');
}

/**
 * Load the recent activities.
 */
function bullseye_event_load_activities() {
	global $base_url;

  $theme_directory = path_to_theme('theme', 'bullseye');
  // Activity Icons.
  $call_icon = $base_url . '/' . $theme_directory . '/images/icons/be_activity_call.svg';
  $send_icon = $base_url . '/' . $theme_directory . '/images/icons/be_activity_send.svg';
  $receive_icon = $base_url . '/' . $theme_directory . '/images/icons/be_activity_receive.svg';
  $meeting_icon = $base_url . '/' . $theme_directory . '/images/icons/be_activity_meeting.svg';
  $converted_icon = $base_url . '/' . $theme_directory . '/images/icons/converted.svg';

  // Task Icons.
  $call_icon_t = $base_url . '/' . $theme_directory . '/images/icons/be_activity_call_orange.svg';
  $send_icon_t = $base_url . '/' . $theme_directory . '/images/icons/be_activity_send_orange.svg';
  $receive_icon_t = $base_url . '/' . $theme_directory . '/images/icons/be_activity_receive_orange.svg';
  $meeting_icon_t = $base_url . '/' . $theme_directory . '/images/icons/be_activity_meeting_orange.svg';

	$nid = $_POST['nid'];
	$filter = $_POST['filter'];

	if ($filter == 'phone_call') {
		$activities = Bullseye::getRecentPhoneCallEventsByNid($nid);
	}
	elseif ($filter == 'meeting') {
		$activities = Bullseye::getRecentMeetingEventsByNid($nid);
	}
	elseif ($filter == 'email') {
		$activities = Bullseye::getRecentEmailEventsByNid($nid);
	}
	elseif ($filter == 'others') {
		$activities = Bullseye::getRecentOthersEventsByNid($nid);
	}
	else {
		$activities = Bullseye::getRecentEventsByNid($nid);
	}

	$sorted = array();

	$be = new Bullseye($user);

	if (!empty($activities)) {
		foreach ($activities as $key => $value) {
	    $date = strtotime($value->field_due_date_value);
	    $value->icon_img = $send_icon;
      $value->description = $value->field_event_name_value . ' with';
      $value->usercolor = 'orange-font';

      if ($value->field_event_type_value == 'activity') {
        // Contact name.
        $contact = Bullseye::getContactDetailsById($value->field_contact_value);
        $firstname = ucwords($contact['field_firstname_value']);
        $lastname = substr($contact['field_lastname_value'], 0, 1);
        $value->contact_name = $firstname . ' ' . strtoupper($lastname) . '.';

        // For the icon and description.
        if ($value->field_task_type_value == 'phone_call') {
          $value->icon_img = $call_icon;
          $value->description = 'Call with';
        }
        elseif ($value->field_task_type_value == 'email') {
          $value->icon_img = $receive_icon;
          $value->description = 'Email to';
        }
        elseif ($value->field_task_type_value == 'meeting') {
          $value->icon_img = $meeting_icon;
          $value->description = 'Meeting with';
        }

        if ($value->field_if_system_generated_value == 'yes') {
          $firstname = $be->getAccountFirstName($value->field_contact_value);
          $firstname = ucwords($firstname);
          $lastname = $be->getAccountLastName($value->field_contact_value);
          $lastname = substr($lastname, 0, 1);
          $value->contact_name = $firstname . ' ' . strtoupper($lastname) . '.';
          $value->description = $value->title . ' by ';
          $value->icon_img = $converted_icon;
        }
      }

      if ($value->field_event_type_value == 'task') {
        $value->icon_img = $send_icon_t;
        $value->usercolor = 'green-font';
        $firstname = $be->getAccountFirstName($value->field_assigned_to_value);
        $firstname = ucwords($firstname);
        $lastname = $be->getAccountLastName($value->field_assigned_to_value);
        $lastname = substr($lastname, 0, 1);
        $value->contact_name = $firstname . ' ' . strtoupper($lastname) . '.';

        // For the icon and description.
        if ($value->field_task_type_value == 'phone_call') {
          $value->icon_img = $call_icon_t;
          $value->description = 'Call with';
        }
        elseif ($value->field_task_type_value == 'email') {
          $value->icon_img = $receive_icon_t;
          $value->description = 'Email by';
        }
        elseif ($value->field_task_type_value == 'meeting') {
          $value->icon_img = $meeting_icon_t;
          $value->description = 'Meeting with';
        }
      }

	    $value->formatted_date = date('M j', strtotime($value->field_due_date_value));
	    $sorted[$date . '-' . $value->nid] = $value;
	  }

	  krsort($sorted);
	}
	
  $vars['nid'] = $nid;
  $vars['activities'] = $sorted;

  $output = theme('be_recent_activities_rows', $vars);

  echo $output;
}

/**
 * Load the recent tasks in calendar tab.
 */
function bullseye_event_calendar_load_tasks() {
  global $user;
  $filter = $_POST['filter'];
  $offset = $_POST['offset'];

  $tasks = Bullseye::getArcherTasks($filter, $offset);

  $sorted = array();

  $be = new Bullseye($user);

  if (!empty($tasks)) {

    foreach ($tasks as $key => $value) {
      $value->dot = '';

      if ($value->field_task_status_value == 'open') {
        $value->dot = 'red-dot';
      }

      // For the task description.
      if ($value->field_task_type_value == 'phone_call') {
        $value->description = 'Call with ';
      }
      elseif ($value->field_task_type_value == 'email') {
        $value->description = 'Email to ';
      }
      elseif ($value->field_task_type_value == 'meeting') {
        $value->description = 'Meeting with ';
      }
      else {
        $value->description = $value->field_event_name_value . ' with ';
      }

      // Assigned to.
      $firstname = $be->getAccountFirstName($value->field_assigned_to_value);
      $firstname = ucwords($firstname);
      $lastname = $be->getAccountLastName($value->field_assigned_to_value);
      $lastname = ucwords($lastname);
      $value->description = $value->description . $firstname . ' ' . $lastname;

      // Task creator.
      $firstname = $be->getAccountFirstName($value->uid);
      $firstname = ucwords($firstname);
      $lastname = $be->getAccountLastName($value->uid);
      $lastname = ucwords($lastname);
      $value->contact_name = $firstname . ' ' . $lastname;

      $value->checkbox_disabled = '';

      if ($be->hasRole('producer', $user->roles)) {
        if ($value->uid != $user->uid) {
          $value->checkbox_disabled = 'disabled';
        }
      }
      if ($value->field_task_status_value == 'closed') {
        $value->checkbox_disabled = 'disabled';
      }

      $value->formatted_date = date('M j', strtotime($value->field_due_date_value));
      $date = strtotime($value->field_due_date_value);
      $sorted[$date . '-' . $value->nid] = $value;
    }

  }

  $vars['tasks'] = $sorted;

  $output = theme('be_calendar_tab_tasks_rows', $vars);

  echo $output;
}

/**
 * Load the recent tasks in calendar tab.
 */
function bullseye_event_calendar_load_activities() {
  global $user;
  $filter = $_POST['filter'];
  $offset = $_POST['offset'];

  $activities = Bullseye::getArcherActivities($filter, $offset);

  $sorted = array();

  $be = new Bullseye($user);

  if (!empty($activities)) {
    foreach ($activities as $key => $value) {

      // Activity creator.
      $firstname = $be->getAccountFirstName($value->uid);
      $firstname = ucwords($firstname);
      $lastname = $be->getAccountLastName($value->uid);
      $lastname = ucwords($lastname);
      $value->contact_name = $firstname . ' ' . $lastname;

      $value->formatted_date = date('M j', strtotime($value->field_due_date_value));
      $date = strtotime($value->field_due_date_value);
      $sorted[$date . '-' . $value->nid] = $value;
    }
  }

  $vars['activities'] = $sorted;

  $output = theme('be_calendar_tab_activities_rows', $vars);

  echo $output;
}

/**
 * Adding the selected tasks to session.
 */
function bullseye_event_selected_tasks() {
  global $user;
  $task_ids = $_POST['task_ids'];
  $remove_ids = $_POST['remove_ids'];

  if (!empty($_SESSION['calendar_tab_tasks_ids_' . $user->uid])) {
    foreach ($task_ids as $key => $value) {
      if (!in_array($value, $_SESSION['calendar_tab_tasks_ids_' . $user->uid])) {
        $_SESSION['calendar_tab_tasks_ids_' . $user->uid][] = $value;
      }
    }
  }
  else {
    $_SESSION['calendar_tab_tasks_ids_' . $user->uid] = $task_ids;
  }

  if (!empty($remove_ids)) {
    foreach ($remove_ids as $key1 => $value1) {
      if (in_array($value1, $_SESSION['calendar_tab_tasks_ids_' . $user->uid])) {
        foreach ($_SESSION['calendar_tab_tasks_ids_' . $user->uid] as $key2 => $value2) {
          if ($value2 == $value1) {
            unset($_SESSION['calendar_tab_tasks_ids_' . $user->uid][$key2]);
          }
        }
      }
    }
  }

  drupal_json_output($_SESSION['calendar_tab_tasks_ids_' . $user->uid]);
}

/**
 * Getting the selected tasks.
 */
function bullseye_event_get_selected_tasks() {
  global $user;
  drupal_json_output($_SESSION['calendar_tab_tasks_ids_' . $user->uid]);
}

/**
 * Override or insert variables into the page templates.
 */
function bullseye_event_preprocess_page(&$vars, $hook) {
  global $base_url;
  $dir = drupal_get_path('module', 'bullseye_event');

  // For company page.
  if (arg(0) == 'company') {
	  $js_path = $base_url . '/' . $dir . '/js/bullseye_event.js';
    drupal_add_js($js_path);
  }

  // For calendar tab.
  if (arg(0) == 'calendar') {
    $js_path = $base_url . '/' . $dir . '/js/bullseye_event_calendar_tab.js';
    drupal_add_js($js_path);
  }

}