<?php
/**
 * Bullseye current progress module.
 */


/**
 * Implements hook_form().
 *
 * Current Progress for Leads Form.
 */
function bullseye_current_progress_leads_form($form, &$form_state) {
  $form = array();

  $form['#attributes']['class'][] = 'be-cp-form';
  
  $form['work_sca_dbra'] = array(
    '#type' => 'radios',
    '#title' => t('Did this lead/company ever work under SCA and/or DBRA?'),
    '#options' => array(
      'yes_sca' => t('Yes, SCA'),
      'yes_dbra' => t('Yes, DBRA'),
      'yes_both' => t('Yes, Both'),
      'no' => t('No'),
    ),
    '#default_value' => 'no',
  );

  $form['plan_to_work_sca_dbra'] = array(
    '#type' => 'radios',
    '#title' => t('Did this lead/company have plans on working under SCA/DBRA in the future?'),
    '#options' => array(
      'yes' => t('Yes'),
      'no' => t('No'),
    ),
    '#default_value' => 'no',
  );

  $form['classify_group'] = array(
    '#type' => 'textarea',
    '#attributes' => array(
      'placeholder' => t('Add a group and press Enter'),
    ),
  );

  $form['submit_container'] = array(
    '#type' => 'container',
  );

  $form['submit_container']['cancel'] = array(
    '#markup' => '<a class="gray-btn" href="/" onClick="parent.Lightbox.end();">Cancel</a>',
  );

  $form['submit_container']['submit'] = array(
    '#type' => 'submit',
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
    '#value' => t('Save'),
  );
  

  return $form;
}

/**
 * Form submit for current progress leads form.
 */
function bullseye_current_progress_leads_form_submit($form, &$form_state) {
  
}

/**
 * Implements hook_theme().
 */
function bullseye_current_progress_theme($existing, $type, $theme, $path) {
  $items['bullseye_current_progress_leads_form'] = array(
    'render element' => 'form',
    'template' => 'cp-leads-form',
    'path' => drupal_get_path('module', 'bullseye_current_progress') . '/templates/',
  );
  return $items;
}
