<?php
/**
 * Bullseye account module.
 */

/**
 * Implements hook_node_update().
 */
function bullseye_account_node_update($node){
  if ($node->type == 'account' && $node->field_account_status[LANGUAGE_NONE[0]['value'] == 'prospect'){
    // Invalidate the existing cache to make sure that
    // the newly added one will get indexed too.
    cache_clear_all('prospect_accounts_listing', 'cache');
  }
}

/**
 * Implements hook_node_insert().
 */
function bullseye_account_node_insert($node) {
  if ($node->type == 'account' && $node->field_account_status[LANGUAGE_NONE[0]['value'] == 'prospect'){
    // Invalidate the existing cache to make sure that
    // the newly added one will get indexed too.
    cache_clear_all('prospect_accounts_listing', 'cache');
  }
}
