<?php
/**
 * Bullseye plan specification module.
 */

// constant access arguments
define('BULLSEYE_PLAN_SPECS_ADD', 'Add plan specification');

/**
 * Implements hook_menu().
 */
function bullseye_plan_specs_menu() {
  $items = array();

  $items['plan_specs'] = array(
    'title' => 'Plan Specifications',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bullseye_plan_specs_form'),
    'access arguments' => array(BULLSEYE_PLAN_SPECS_ADD),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
/**
 * implementation of hook permission
 */
function bullseye_plan_specs_permission(){
  return array(
    BULLSEYE_PLAN_SPECS_ADD => array(
      'title' => t(BULLSEYE_PLAN_SPECS_ADD),
      'description' => t('Allow users on adding plan specifications.'),
    ),
  );
}

/**
 * Implements hook_form().
 *
 * Add plan specifciation form
 */
function bullseye_plan_specs_form($form, &$form_state) {

  global $user;

  $be = new Bullseye($user);

  // Company info default values.
  $company_name = '';
  $primary_contact = '';
  $title = '';
  $contact_number = '';
  $nid = '';

  // Plan specs default values.
  $plan_specs_nid = '';
  $fringe_rates = '';
  $proposed_effective_date = '';
  $other_work_locations = '';
  $number_of_employees = '';
  $number_of_dependents = '';
  $nature_of_business = '';
  $years_in_business = '';
  $tax_id = '';
  $renewal_date = '';
  $benefits = array();
  $special_benefits_text = '';

  // Check if link is from current progress send link email.
  // If yes, then pre-populate some fields.
  if (isset($_GET['company_nid']) && !empty($_GET['company_nid'])) {
    $nid = $_GET['company_nid'];
    $node = node_load($nid);
    $company_name = $node->title;
    $contact = Bullseye::getAccountPrimaryContact($nid);
    $primary_contact = $contact['field_email_value'];
    $title = $contact['field_position_value'];
    $contact_number = $contact['field_mobile_phone_value'];

    // Check if account has existing plan specs submitted.
    $plan_specs = $be->getLatestPlanSpecsByNid($nid);
    if (!empty($plan_specs)) {
      $plan_specs_nid = $plan_specs['nid'];
      $fringe_rates = $plan_specs['field_fringe_rate_value'];
      $proposed_effective_date = $plan_specs['field_proposed_effective_date_value'];
      $other_work_locations = $plan_specs['field_other_work_locations_value'];
      $number_of_employees = $plan_specs['field_number_of_employees_value'];
      $number_of_dependents = $plan_specs['field_number_of_dependents_value'];
      $nature_of_business = $plan_specs['field_nature_of_business_sic_value'];
      $years_in_business = $plan_specs['field_years_in_business_value'];
      $tax_id = $plan_specs['field_tax_id_value'];
      $renewal_date = $plan_specs['field_renewal_date_value'];
      $special_benefits_text = $plan_specs['field_others_value'];
      foreach ($plan_specs['benefits'] as $key => $value) {
        $benefits[] = $value;
      }
    }
  }

  $form = array();

  $form['#attributes']['class'][] = 'be-forms be-forms-custom';

  $form['nid'] = array(
    '#type' => 'hidden',
    '#value' => $nid,
  );

  $form['plan_specs_nid'] = array(
    '#type' => 'hidden',
    '#value' => $plan_specs['nid'],
  );

  $form['company_container'] = array(
    '#type' => 'container',
  );

  $form['company_container']['contact_company'] = array(
    '#type' => 'textfield',
    '#title' => t('Company Name'),
    '#attributes' => array(
      'placeholder' => t('Add Company'),
    ),
    '#default_value' => $company_name,
  );

  $form['company_container']['contact'] = array(
    '#type' => 'textfield',
    '#title' => t('Primary Contact'),
    '#attributes' => array(
      'placeholder' => t('Add Contact'),
    ),
    '#default_value' => $primary_contact,
  );

  $form['company_container']['contact_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#attributes' => array(
      'placeholder' => t('Add Title'),
    ),
    '#default_value' => $title,
  );

  $form['company_container']['contact_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Contact Number'),
    '#attributes' => array(
      'placeholder' => t('Add Phone Number'),
    ),
    '#default_value' => $contact_number,
  );

  $form['company_container']['contact_industry'] = array(
    '#type' => 'textfield',
    '#title' => t('Industry'),
    '#attributes' => array(
      'placeholder' => t('Add Industry, Separated by commas'),
    ),
  );

  $form['company_container']['contact_address'] = array(
    '#type' => 'textfield',
    '#title' => t('Complete Address'),
    '#attributes' => array(
      'placeholder' => t('Add Address'),
    ),
  );

  $form['plan_specs'] = array(
    '#type' => 'container',
  );

  $form['plan_specs']['plan_fringe_rates'] = array(
    '#type' => 'textfield',
    '#title' => t('Fringe Rate/s'),
    '#attributes' => array(
      'placeholder' => t('$4.27, $5.03'),
    ),
    '#default_value' => $fringe_rates,
  );

  // @todo: add date javascript handler
  $form['plan_specs']['plan_proposed_date'] = array(
    '#title' => t('Proposed Effective Date'),
    '#type' => 'date_popup',
    '#attributes' => array(
      'placeholder' => t('mm/dd/yyyy'),
    ),
    '#date_format' => 'm/d/Y',
    '#timepicker_options' => array(
      'beforeShow' => 'planSpecsDateRenewal',
      'rows' => 6,
      'showCloseButton' => TRUE,
      'closeButtonText' => t('Close'),
    ),
    '#default_value' => $proposed_effective_date,
  );

  $form['plan_specs']['plan_other_location'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Work Location and Zip Codes'),
    '#attributes' => array(
      'placeholder' => t('Dallas 88829, New Jersey 81920'),
    ),
    '#default_value' => $other_work_locations,
  );

  $form['plan_specs']['plan_num_employees'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Employees'),
    '#attributes' => array(
      'placeholder' => t('200'),
    ),
    '#default_value' => $number_of_employees,
  );

  $form['plan_specs']['plan_num_dependents'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Dependents'),
    '#attributes' => array(
      'placeholder' => t('100'),
    ),
    '#default_value' => $number_of_dependents,
  );

  $form['plan_specs']['plan_nature_business'] = array(
    '#type' => 'textfield',
    '#title' => t('Nature of Business/SIC'),
    '#attributes' => array(
      'placeholder' => t('xxxx'),
    ),
    '#default_value' => $nature_of_business,
  );

  $form['plan_specs']['plan_years_business'] = array(
    '#type' => 'textfield',
    '#title' => t('Years in Business'),
    '#attributes' => array(
      'placeholder' => t('5'),
    ),
    '#default_value' => $years_in_business,
  );

  $form['plan_specs']['plan_tax_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Tax ID'),
    '#attributes' => array(
      'placeholder' => t('XX-XXXXXXX'),
    ),
    '#default_value' => $tax_id,
  );

  // @todo: add date javascript handler
  $form['plan_specs']['plan_renewal_date'] = array(
    '#type' => 'date_popup',
    '#title' => t('Renewal Date'),
    '#attributes' => array(
      'placeholder' => t('mm/dd/yyyy'),
    ),
    '#date_format' => 'm/d/Y',
    '#timepicker_options' => array(
      'beforeShow' => 'planSpecsDateRenewal',
      'rows' => 6,
      'showCloseButton' => TRUE,
      'closeButtonText' => t('Close'),
    ),
    '#default_value' => $renewal_date,
  );

  $form['benefits'] = array(
    '#type' => 'container',
  );

  $form['benefits']['benefits_in'] = array(
    '#type' => 'checkboxes',
    '#options' => array(
      'major_medical' => t('Major Medical'),
      'teledoc' => t('Telemedicine'),
      'life' => t('Life & AD&D'),
      'dental' => t('Dental'),
      'limited_medical' => t('Limited Medical'),
      'mec' => t('MEC'),
      'short_term_disability' => t('Short Term Disability'),
      'vision' => t('Vision'),
      'retirement' => t('Retirement'),
      'special_benefits' => t('Specialty Benefits'),
    ),
    '#default_value' => $benefits,
  );

  $form['benefits']['benefits_in_others'] = array(
    '#type' => 'textfield',
  );

  $form['submit_container'] = array(
    '#type' => 'container',
  );

  $form['submit_container']['submit'] = array(
    '#type' => 'submit',
    '#attributes' => array(
      'class' => array('green-btn'),
    ),
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * Implements hook_FORM_submit().
 */
function bullseye_plan_specs_form_submit($form, &$form_state) {
  global $user;
  $be = new Bullseye($user);
  $data = $form_state['values'];

  // Add plan specs if no existing yet.
  if ($form_state['values']['plan_specs_nid'] == NULL) {
    $be->createPlanSpecs($data);
  }
  else {
    // Update the existing plan specs if there is existing.
    $be->updatePlanSpecs($data);
  }

}
